import mongoose, { type ClientSession } from 'mongoose';
import Notification from '../models/notifications.model';
import NotificationRecipient from '../models/notification-recipient.model';
import notificationDeliveryService from './notification-delivery.service';
import { INotificationAudienceEnum, INotificationRecipientModelEnum, INotificationStatusEnum, type INotification } from '../interfaces/notification.interface';
import Patient from '../models/patients.model'; import Nurse from '../models/nurse.model'; import { INotificationCategoryEnum, INotificationPrivacyEnum, INotificationTypeEnum } from '../interfaces/notification.interface';

type Input = { userIds: readonly (mongoose.Types.ObjectId | string)[]; dedupeKey: string; session?: ClientSession; payload: Partial<INotification> };
class DomainNotificationService {
    async targeted({ userIds, dedupeKey, session, payload }: Input) { const ids = [...new Set(userIds.map(String))].map(id => new mongoose.Types.ObjectId(id)); if (!ids.length) return null; try { const created = await Notification.create([{ ...payload, audience: INotificationAudienceEnum.TARGETED, recipient_ids: [], recipient_model: INotificationRecipientModelEnum.USER, dedupe_key: dedupeKey, status: INotificationStatusEnum.PENDING, is_read: false, visible_at: payload.visible_at ?? new Date(), expires_at: payload.expires_at ?? new Date(Date.now() + 7776000000) }], session ? { session } : undefined); const notification = created[0]!; await NotificationRecipient.insertMany(ids.map(user_id => ({ notification_id: notification._id, user_id, expires_at: notification.expires_at })), session ? { session, ordered: true } : { ordered: true }); await notificationDeliveryService.enqueueForNotification(notification, session); return notification; } catch (error: any) { if (error?.code !== 11000) throw error; return Notification.findOne({ dedupe_key: dedupeKey }).session(session ?? null).exec(); } }
    async homeCare(request: any, event: string, profileIds: any[], session: ClientSession) { const [patient, ...nurses] = await Promise.all([Patient.findById(request.patient_id).select('user_id').session(session).lean().exec(), ...profileIds.filter(Boolean).map(id => Nurse.findById(id).select('user_id').session(session).lean().exec())]); if (!patient?.user_id || nurses.some(n => !n?.user_id)) throw new Error('HOME_CARE_NOTIFICATION_IDENTITY_MISSING'); const titles: any = { assigned: 'تم تعيين الممرض', on_the_way: 'الممرض في الطريق', arrived: 'وصل الممرض', in_progress: 'بدأت الخدمة', completed: 'اكتملت الخدمة', reassigned: 'تم تحديث الممرض المكلّف بالخدمة', unassigned: 'طلبك بانتظار تعيين ممرض' }; const users = [patient.user_id, ...nurses.map(n => n!.user_id)]; for (const userId of users) await this.targeted({ userIds: [userId], session, dedupeKey: `home-care:${request._id}:${request.dispatch.version}:${event}:${userId}`, payload: { category: INotificationCategoryEnum.SERVICES, privacy: INotificationPrivacyEnum.SENSITIVE, type: event === 'on_the_way' ? INotificationTypeEnum.HOME_CARE_ON_THE_WAY : event === 'arrived' ? INotificationTypeEnum.HOME_CARE_ARRIVED : event === 'in_progress' ? INotificationTypeEnum.HOME_CARE_IN_PROGRESS : event === 'completed' ? INotificationTypeEnum.HOME_CARE_COMPLETED : INotificationTypeEnum.HOME_CARE_ASSIGNED, title: titles[event] ?? 'تم تحديث طلب الرعاية المنزلية', body: titles[event] ?? 'تم تحديث حالة طلب الرعاية المنزلية', source: { domain: 'home_care_request', id: request._id }, target: { type: 'home_care_request', id: request._id } } }); }
}
export default new DomainNotificationService();
