import mongoose, { type ClientSession } from 'mongoose';
import Notification from '../models/notifications.model';
import NotificationRecipient from '../models/notification-recipient.model';
import notificationDeliveryService from './notification-delivery.service';
import { INotificationAudienceEnum, INotificationRecipientModelEnum, INotificationStatusEnum, type INotification } from '../interfaces/notification.interface';
import Patient from '../models/patients.model'; import Nurse from '../models/nurse.model'; import Pharmacy from '../models/pharmacy.model'; import { INotificationCategoryEnum, INotificationPrivacyEnum, INotificationTypeEnum } from '../interfaces/notification.interface';

type Input = { userIds: readonly (mongoose.Types.ObjectId | string)[]; dedupeKey: string; session?: ClientSession; payload: Partial<INotification> };
export type HomeCareRecipientMode = 'patient' | 'patient_and_nurses' | 'nurses';
export type PharmacyRecipientMode = 'patient' | 'patient_and_pharmacies' | 'pharmacies';
export interface HomeCareDomainNotifier {
    homeCare(request: any, event: string, profileIds: any[], session: ClientSession, recipientMode?: HomeCareRecipientMode): Promise<unknown>;
}
export interface PharmacyDomainNotifier {
    pharmacy(request: any, event: string, profileIds: any[], session: ClientSession, recipientMode?: PharmacyRecipientMode): Promise<unknown>;
}
export class DomainNotificationService implements HomeCareDomainNotifier, PharmacyDomainNotifier {
    async targeted({ userIds, dedupeKey, session, payload }: Input) { const ids = [...new Set(userIds.map(String))].map(id => new mongoose.Types.ObjectId(id)); if (!ids.length) return null; try { const created = await Notification.create([{ ...payload, audience: INotificationAudienceEnum.TARGETED, recipient_ids: [], recipient_model: INotificationRecipientModelEnum.USER, dedupe_key: dedupeKey, status: INotificationStatusEnum.PENDING, is_read: false, visible_at: payload.visible_at ?? new Date(), expires_at: payload.expires_at ?? new Date(Date.now() + 7776000000) }], session ? { session } : undefined); const notification = created[0]!; await NotificationRecipient.insertMany(ids.map(user_id => ({ notification_id: notification._id, user_id, expires_at: notification.expires_at })), session ? { session, ordered: true } : { ordered: true }); await notificationDeliveryService.enqueueForNotification(notification, session); return notification; } catch (error: any) { if (error?.code !== 11000) throw error; return Notification.findOne({ dedupe_key: dedupeKey }).session(session ?? null).exec(); } }
    async homeCare(request: any, event: string, profileIds: any[], session: ClientSession, recipientMode: HomeCareRecipientMode = 'patient_and_nurses') { const [patient, ...nurses] = await Promise.all([Patient.findById(request.patient_id).select('user_id').session(session).lean().exec(), ...profileIds.filter(Boolean).map(id => Nurse.findById(id).select('user_id').session(session).lean().exec())]); if ((recipientMode !== 'nurses' && !patient?.user_id) || nurses.some(n => !n?.user_id)) throw new Error('HOME_CARE_NOTIFICATION_IDENTITY_MISSING'); const titles: any = { confirmed: 'تم تأكيد طلب الرعاية المنزلية', assigned: 'تم تعيين الممرض', on_the_way: 'الممرض في الطريق', arrived: 'وصل الممرض', in_progress: 'بدأت الخدمة', completed: 'اكتملت الخدمة', reassigned: 'تم تحديث الممرض المكلّف بالخدمة', unassigned: 'طلبك بانتظار تعيين ممرض', cancelled: 'تم إلغاء طلب الرعاية المنزلية', rejected: 'تم رفض طلب الرعاية المنزلية' }; const users = recipientMode === 'patient' ? [patient!.user_id] : recipientMode === 'nurses' ? nurses.map(n => n!.user_id) : [patient!.user_id, ...nurses.map(n => n!.user_id)]; const type = event === 'confirmed' ? INotificationTypeEnum.HOME_CARE_CONFIRMED : event === 'cancelled' ? INotificationTypeEnum.HOME_CARE_CANCELLED : event === 'rejected' ? INotificationTypeEnum.HOME_CARE_REJECTED : event === 'on_the_way' ? INotificationTypeEnum.HOME_CARE_ON_THE_WAY : event === 'arrived' ? INotificationTypeEnum.HOME_CARE_ARRIVED : event === 'in_progress' ? INotificationTypeEnum.HOME_CARE_IN_PROGRESS : event === 'completed' ? INotificationTypeEnum.HOME_CARE_COMPLETED : INotificationTypeEnum.HOME_CARE_ASSIGNED; for (const userId of users) await this.targeted({ userIds: [userId], session, dedupeKey: `home-care:${request._id}:${request.dispatch.version}:${event}:${userId}`, payload: { category: INotificationCategoryEnum.SERVICES, privacy: INotificationPrivacyEnum.SENSITIVE, type, title: titles[event] ?? 'تم تحديث طلب الرعاية المنزلية', body: titles[event] ?? 'تم تحديث حالة طلب الرعاية المنزلية', source: { domain: 'home_care_request', id: request._id }, target: { type: 'home_care_request', id: request._id } } }); }
    async pharmacy(request: any, event: string, profileIds: any[], session: ClientSession, recipientMode: PharmacyRecipientMode = 'patient_and_pharmacies') { const [patient, ...pharmacies] = await Promise.all([Patient.findById(request.patient_id).select('user_id').session(session).lean().exec(), ...profileIds.filter(Boolean).map(id => Pharmacy.findById(id).select('user_id').session(session).lean().exec())]); if ((recipientMode !== 'pharmacies' && !patient?.user_id) || pharmacies.some(pharmacy => !pharmacy?.user_id)) throw new Error('PHARMACY_NOTIFICATION_IDENTITY_MISSING'); const titles: any = { under_review: 'طلبك قيد المراجعة', assigned: 'تم تعيين طلب جديد', reassigned: 'تم تعيين طلب جديد', unassigned: 'تمت إعادة فتح طلبك', quotation_ready: 'عرض الصيدلية جاهز', quotation_declined: 'تم رفض عرض السعر', confirmed: 'تم تأكيد طلبك', preparing: 'جاري تجهيز طلبك', ready_for_delivery: 'طلبك جاهز للتوصيل', out_for_delivery: 'طلبك في الطريق', delivered: 'تم تسليم طلبك', cancelled: 'تم إلغاء طلب الصيدلية', rejected: 'تم رفض الطلب', reopened: 'تمت إعادة فتح طلبك' }; const users = recipientMode === 'patient' ? [patient!.user_id] : recipientMode === 'pharmacies' ? pharmacies.map(pharmacy => pharmacy!.user_id) : [patient!.user_id, ...pharmacies.map(pharmacy => pharmacy!.user_id)]; const type = event === 'quotation_ready' ? INotificationTypeEnum.PHARMACY_QUOTATION_READY : event === 'quotation_declined' ? INotificationTypeEnum.PHARMACY_QUOTATION_DECLINED : event === 'confirmed' ? INotificationTypeEnum.PHARMACY_CONFIRMED : event === 'preparing' ? INotificationTypeEnum.PHARMACY_PREPARING : event === 'ready_for_delivery' ? INotificationTypeEnum.PHARMACY_READY_FOR_DELIVERY : event === 'out_for_delivery' ? INotificationTypeEnum.PHARMACY_OUT_FOR_DELIVERY : event === 'delivered' ? INotificationTypeEnum.PHARMACY_DELIVERED : event === 'cancelled' ? INotificationTypeEnum.PHARMACY_CANCELLED : event === 'rejected' ? INotificationTypeEnum.PHARMACY_REJECTED : event === 'reopened' ? INotificationTypeEnum.PHARMACY_REOPENED : INotificationTypeEnum.PHARMACY_UNDER_REVIEW; for (const userId of users) await this.targeted({ userIds: [userId], session, dedupeKey: `pharmacy:${request._id}:${request.workflowVersion}:${event}:${userId}`, payload: { category: INotificationCategoryEnum.MEDICATIONS, privacy: INotificationPrivacyEnum.SENSITIVE, type, title: titles[event] ?? 'تم تحديث طلب الصيدلية', body: titles[event] ?? 'تم تحديث حالة طلب الصيدلية', source: { domain: 'pharmacy_treatment_request', id: request._id }, target: { type: 'pharmacy_treatment_request', id: request._id } } }); }
}
export default new DomainNotificationService();
