import mongoose, { type ClientSession, type FilterQuery } from 'mongoose';
import Request, { type PharmacyTreatmentRequestDocument } from '../models/pharmacy-treatment-request.model';
import Counter from '../models/pharmacy-treatment-request-counter.model';
import History from '../models/pharmacy-treatment-request-history.model';
import pharmacyService from './pharmacy.service';
import patientChildService from './patient-child.service';
import { PatientChildStatusEnum } from '../interfaces/patient-child.interface';
import { PharmacyDispatchModeEnum as Mode, PharmacyDispatchStatusEnum as DS, PharmacyRequestStatusEnum as S, type IPharmacyTreatmentRequest, type PharmacyQuotation, type PharmacyRequestStatus } from '../interfaces/pharmacy-treatment-request.interface';
import { DomainError } from './domain-error';
import ActivityLogService from './activity-log.service';
import { IActivityLogActionEnum, IActivityLogSourceEnum } from '../interfaces/activity-log.interface';
import transactionRunner, { type PharmacyTransactionRunner } from './pharmacy-transaction.service';
import { assertPharmacyTransition, PharmacyHistoryEventEnum as Event, PharmacyWorkflowOperationEnum as Op, type PharmacyWorkflowOperation } from './pharmacy-treatment-request.workflow';
import uploadPolicyService from './upload-policy.service'; import {UploadPurposeEnum} from '../constants/upload-policy';
import { safeSearchPattern } from './search-safety.service';
import domainNotificationService from './domain-notification.service';

export interface RxActor { user_id:string; type:'PATIENT'|'PHARMACY'|'ADMIN'; pharmacy_id?:string; endpoint:string }
export interface QuoteInput { items:{name:string;quantity:number;unit_price:number;note?:string|null}[]; unavailable_items?:{name:string;note?:string|null}[]; delivery_fee:number; discount:number; pharmacy_note?:string|null }
type ListQuery = { page?:number|string; limit?:number|string; status?:PharmacyRequestStatus; dateFrom?:string; dateTo?:string; [key:string]:unknown };

const populated = (q:any) => q.populate({path:'patient_id',select:'full_name phone profile_photo'}).populate({path:'child_id',select:'full_name date_of_birth status'}).populate({path:'dispatch.pharmacy_id',select:'name display_name logo phone license_verified status'});
const openFilter = () => ({$and:[{$or:[{'dispatch.status':DS.OPEN},{'dispatch.status':{$exists:false}}]},{$or:[{'dispatch.pharmacy_id':null},{'dispatch.pharmacy_id':{$exists:false}}]}]});
const oid = (value:string) => { if(!mongoose.Types.ObjectId.isValid(value)) throw new DomainError('المعرف غير صالح',400,'INVALID_IDENTIFIER'); return new mongoose.Types.ObjectId(value); };
const clean = (value:unknown,max:number) => { if(value===null||value===undefined)return null; const result=String(value).normalize('NFKC').trim(); if(result.length>max)throw new DomainError('النص طويل جداً',400,'INVALID_INPUT'); return result||null; };
const inSession = <T extends {session:(session:ClientSession)=>T}>(query:T,session:ClientSession|null) => session ? query.session(session) : query;
const stale = (message='تم تحديث الطلب بواسطة مستخدم آخر',code='STALE_WORKFLOW_VERSION') => new DomainError(message,409,code);

export async function nextPharmacyRequestNumber(now=new Date(),session:ClientSession|null=null){
    const year=now.getUTCFullYear();
    const query=Counter.findOneAndUpdate({_id:`pharmacy_request:${year}`},{$inc:{sequence:1}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});
    const counter=await inSession(query as any,session).exec();
    if(!counter)throw new Error('Pharmacy request counter failed');
    return `RX-${year}-${String(counter.sequence).padStart(6,'0')}`;
}

export function calculateQuotation(input:QuoteInput){
    const items=input.items.map(item=>{const name=item.name.trim();if(!name||!Number.isSafeInteger(item.quantity)||item.quantity<1||!Number.isSafeInteger(item.unit_price)||item.unit_price<0)throw new DomainError('بيانات عرض السعر غير صالحة',400,'INVALID_QUOTATION');const line_total=item.quantity*item.unit_price;if(!Number.isSafeInteger(line_total))throw new DomainError('قيمة عرض السعر غير صالحة',400,'INVALID_QUOTATION');return{name,quantity:item.quantity,unit_price:item.unit_price,line_total,note:clean(item.note,500)}});
    if(!items.length||!Number.isSafeInteger(input.delivery_fee)||input.delivery_fee<0||!Number.isSafeInteger(input.discount)||input.discount<0)throw new DomainError('قيم عرض السعر غير صالحة',400,'INVALID_QUOTATION');
    const unavailable_items=(input.unavailable_items??[]).map(item=>{const name=item.name.trim();if(!name)throw new DomainError('بيانات عرض السعر غير صالحة',400,'INVALID_QUOTATION');return{name,note:clean(item.note,500)}});
    const medicines_subtotal=items.reduce((total,item)=>total+item.line_total,0),total_price=medicines_subtotal+input.delivery_fee-input.discount;
    if(!Number.isSafeInteger(medicines_subtotal)||!Number.isSafeInteger(total_price)||total_price<0)throw new DomainError('الخصم غير صالح',400,'INVALID_QUOTATION');
    return{items,unavailable_items,medicines_subtotal,delivery_fee:input.delivery_fee,discount:input.discount,total_price,pharmacy_note:clean(input.pharmacy_note,2000)};
}

export class PharmacyTreatmentRequestService {
    constructor(
        private readonly transactions:PharmacyTransactionRunner=transactionRunner,
        private readonly historyWriter:{create:(entries:any[],options?:any)=>Promise<unknown>}=History as any,
    ) {}

    async create(patientId:mongoose.Types.ObjectId,input:any,actor:RxActor){
        const requestedImages=[...new Set<string>((input.prescription_images??[]).map((x:string)=>x.trim()).filter(Boolean))];
        const imageAssets=await Promise.all(requestedImages.map(reference=>uploadPolicyService.requireReadyReference(reference,UploadPurposeEnum.PRESCRIPTION_IMAGE,'PATIENT',String(patientId))));
        const images=imageAssets.map(asset=>asset!.upload_id),details=clean(input.treatment_details,3000);
        if(images.length>5)throw new DomainError('الحد الأقصى خمس صور',400,'INVALID_PRESCRIPTION_IMAGES');
        if(!images.length&&!details)throw new DomainError('يجب إرفاق وصفة أو تفاصيل العلاج',422,'TREATMENT_CONTENT_REQUIRED');
        let child:null|mongoose.Types.ObjectId=null;
        if(input.child_id){const owned=await patientChildService.requireOwnedChild(patientId,input.child_id);if(owned.status!==PatientChildStatusEnum.ACTIVE)throw new DomainError('الطفل غير فعال',422,'CHILD_NOT_ACTIVE');child=new mongoose.Types.ObjectId(String(owned._id));}
        const address=input.delivery_address;
        if(!address||String(address.address_text).trim().length<5||address.lat< -90||address.lat>90||address.lng< -180||address.lng>180)throw new DomainError('عنوان التوصيل غير صالح',400,'INVALID_DELIVERY_ADDRESS');
        const base={patient_id:patientId,child_id:child,prescription_images:images,treatment_details:details,delivery_address:{address_text:String(address.address_text).trim(),lat:address.lat,lng:address.lng},delivery_phone:String(input.delivery_phone).trim(),notes:clean(input.notes,2000),preferred_payment_method:input.preferred_payment_method,status:S.OPEN,workflowVersion:0,dispatch:{status:DS.OPEN,mode:Mode.OPEN_POOL,pharmacy_id:null,assigned_at:null,assigned_by_user_id:null,version:0},quotation:null,accepted_quotation:null,excluded_pharmacy_ids:[]};
        let created!:PharmacyTreatmentRequestDocument;
        for(let attempt=0;attempt<3;attempt++){
            try{
                const requestNumber=await nextPharmacyRequestNumber();
                created=await this.transactions.run(async session=>{const [request]=await Request.create([{...base,request_number:requestNumber}],session?{session}:{});await this.appendHistory(request,Event.CREATED,actor,null,S.OPEN,null,null,null,null,session);return request;});
                break;
            }catch(error:any){if(error?.code!==11000||attempt===2)throw error;}
        }
        await this.audit(created,actor,'POST',input);
        await Promise.all(imageAssets.map(asset=>uploadPolicyService.markAttached(asset,String(created._id),'prescription_images')));
        return await this.getPatient(patientId,String(created._id))??created;
    }

    async listPatient(patientId:mongoose.Types.ObjectId,q:ListQuery){return this.list({patient_id:patientId},q);}
    async getPatient(patientId:mongoose.Types.ObjectId,id:string){if(!mongoose.Types.ObjectId.isValid(id))return null;return populated(Request.findOne({_id:id,patient_id:patientId})).exec();}
    async listAvailable(userId:string,q:ListQuery){const pharmacy=await pharmacyService.requireOperational(userId);return this.list({status:S.OPEN,...openFilter(),excluded_pharmacy_ids:{$ne:pharmacy._id}},q,true);}
    async listMine(userId:string,q:ListQuery){const pharmacy=await pharmacyService.requireOperational(userId);return this.list({'dispatch.pharmacy_id':pharmacy._id},q);}
    async getPharmacy(userId:string,id:string){const pharmacy=await pharmacyService.requireOperational(userId);if(!mongoose.Types.ObjectId.isValid(id))return null;return populated(Request.findOne({_id:id,'dispatch.pharmacy_id':pharmacy._id})).exec();}

    async claim(userId:string,id:string,actor:RxActor){
        const pharmacy=await pharmacyService.requireOperational(userId),scoped={...actor,pharmacy_id:String(pharmacy._id)};
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findOne({_id:oid(id),status:S.OPEN,...openFilter(),excluded_pharmacy_ids:{$ne:pharmacy._id}}) as any,session).exec();if(!current)throw new DomainError('تم استلام الطلب من قبل صيدلية أخرى',409,'REQUEST_ALREADY_CLAIMED');assertPharmacyTransition(Op.CLAIM,'PHARMACY',current.status);const updated=await inSession(Request.findOneAndUpdate({_id:current._id,status:S.OPEN,workflowVersion:current.workflowVersion,excluded_pharmacy_ids:{$ne:pharmacy._id},...openFilter()},{$set:{status:S.UNDER_REVIEW,'dispatch.status':DS.CLAIMED,'dispatch.mode':Mode.OPEN_POOL,'dispatch.pharmacy_id':pharmacy._id,'dispatch.assigned_at':new Date(),'dispatch.assigned_by_user_id':null},$inc:{workflowVersion:1,'dispatch.version':1}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw new DomainError('تم استلام الطلب من قبل صيدلية أخرى',409,'REQUEST_ALREADY_CLAIMED');await this.appendHistory(updated,Event.CLAIMED,scoped,S.OPEN,S.UNDER_REVIEW,null,pharmacy._id,null,null,session);await domainNotificationService.pharmacy(updated,'under_review',[],session!,'patient');return updated;});
        await this.audit(result,scoped,'PATCH',{});return result;
    }

    async quote(userId:string,id:string,input:QuoteInput,actor:RxActor){
        const pharmacy=await pharmacyService.requireOperational(userId),calculated=calculateQuotation(input),scoped={...actor,pharmacy_id:String(pharmacy._id)};
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findOne({_id:oid(id),'dispatch.pharmacy_id':pharmacy._id,status:{$in:[S.UNDER_REVIEW,S.WAITING_CUSTOMER_APPROVAL]}}) as any,session).exec();if(!current)throw new DomainError('الطلب غير موجود أو لا يمكن تسعيره',404,'PHARMACY_REQUEST_NOT_FOUND');const operation=current.quotation?Op.REVISE_QUOTE:Op.QUOTE;assertPharmacyTransition(operation,'PHARMACY',current.status);const version=(current.quotation?.version??0)+1,quotation={...calculated,version,pharmacy_id:pharmacy._id,quoted_at:new Date(),accepted_at:null};const versionFilter=current.quotation?{'quotation.version':current.quotation.version}:{'quotation.version':{$exists:false}};const updated=await inSession(Request.findOneAndUpdate({_id:current._id,status:current.status,workflowVersion:current.workflowVersion,'dispatch.pharmacy_id':pharmacy._id,'dispatch.version':current.dispatch.version,...versionFilter},{$set:{status:S.WAITING_CUSTOMER_APPROVAL,quotation},$inc:{workflowVersion:1,'dispatch.version':1}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw stale();await this.appendHistory(updated,version===1?Event.QUOTATION_CREATED:Event.QUOTATION_REVISED,scoped,current.status,S.WAITING_CUSTOMER_APPROVAL,pharmacy._id,pharmacy._id,null,{quotation:this.quoteSnapshot(quotation),previous_quotation:this.quoteSnapshot(current.quotation)},session);await domainNotificationService.pharmacy(updated,'quotation_ready',[],session!,'patient');return updated;});
        await this.audit(result,scoped,'POST',calculated);return result;
    }

    async decide(patientId:mongoose.Types.ObjectId,id:string,version:number,accept:boolean,reason:string|undefined,actor:RxActor){
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findOne({_id:oid(id),patient_id:patientId}) as any,session).exec();if(!current)throw new DomainError('الطلب غير موجود',404,'PHARMACY_REQUEST_NOT_FOUND');const pharmacyId=current.dispatch?.pharmacy_id;if(!pharmacyId||!current.quotation)throw new DomainError('عرض السعر غير متاح',409,'QUOTATION_NOT_ACTIVE');assertPharmacyTransition(accept?Op.ACCEPT_QUOTE:Op.REJECT_QUOTE,'PATIENT',current.status);const snapshot=this.quoteSnapshot(current.quotation,true);const now=new Date();const set:any=accept?{status:S.CONFIRMED,'quotation.accepted_at':now,accepted_quotation:{...snapshot,accepted_at:now}}:{status:S.OPEN,quotation:null,'dispatch.status':DS.OPEN,'dispatch.mode':Mode.OPEN_POOL,'dispatch.pharmacy_id':null,'dispatch.assigned_at':null,'dispatch.assigned_by_user_id':null};const update:any={$set:set,$inc:{workflowVersion:1,'dispatch.version':1}};if(!accept)update.$addToSet={excluded_pharmacy_ids:pharmacyId};const updated=await inSession(Request.findOneAndUpdate({_id:current._id,patient_id:patientId,status:S.WAITING_CUSTOMER_APPROVAL,workflowVersion:current.workflowVersion,'quotation.version':version,'quotation.pharmacy_id':pharmacyId,'dispatch.pharmacy_id':pharmacyId},update,{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw stale('تم تحديث العرض، يرجى مراجعة السعر الجديد','STALE_QUOTATION_VERSION');await this.appendHistory(updated,accept?Event.QUOTATION_ACCEPTED:Event.QUOTATION_REJECTED,actor,current.status,updated.status,pharmacyId,accept?pharmacyId:null,reason,{quotation:snapshot},session);await domainNotificationService.pharmacy(updated,accept?'confirmed':'quotation_declined',[pharmacyId],session!,accept?'patient_and_pharmacies':'pharmacies');return updated;});
        await this.audit(result,actor,'PATCH',{version,reason});return result;
    }

    async transition(userId:string,id:string,expected:PharmacyRequestStatus,next:PharmacyRequestStatus,actor:RxActor){
        const pharmacy=await pharmacyService.requireOperational(userId),operation=this.lifecycleOperation(expected,next),scoped={...actor,pharmacy_id:String(pharmacy._id)};
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findOne({_id:oid(id),'dispatch.pharmacy_id':pharmacy._id}) as any,session).exec();if(!current)throw new DomainError('الطلب غير موجود',404,'PHARMACY_REQUEST_NOT_FOUND');assertPharmacyTransition(operation,'PHARMACY',current.status);if(!current.accepted_quotation||String(current.accepted_quotation.pharmacy_id)!==String(pharmacy._id))throw new DomainError('بيانات عرض السعر المقبول غير مكتملة',409,'ACCEPTED_QUOTATION_REQUIRED');const set:any={status:next};if(next===S.DELIVERED)set['dispatch.status']=DS.CLOSED;const updated=await inSession(Request.findOneAndUpdate({_id:current._id,status:expected,workflowVersion:current.workflowVersion,'dispatch.pharmacy_id':pharmacy._id,'dispatch.status':DS.CLAIMED,'accepted_quotation.version':current.accepted_quotation.version,'accepted_quotation.pharmacy_id':pharmacy._id},{$set:set,$inc:{workflowVersion:1,'dispatch.version':1}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw stale();await this.appendHistory(updated,next===S.DELIVERED?Event.DELIVERED:Event.STATUS_CHANGED,scoped,expected,next,pharmacy._id,pharmacy._id,null,null,session);await domainNotificationService.pharmacy(updated,next,[],session!,'patient');return updated;});
        await this.audit(result,scoped,'PATCH',{});return result;
    }

    async cancelPatient(patientId:mongoose.Types.ObjectId,id:string,reason:string|undefined,actor:RxActor){
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findOne({_id:oid(id),patient_id:patientId}) as any,session).exec();if(!current)throw new DomainError('الطلب غير موجود',404,'PHARMACY_REQUEST_NOT_FOUND');const previousPharmacyId=current.dispatch.pharmacy_id;assertPharmacyTransition(Op.PATIENT_CANCEL,'PATIENT',current.status);const updated=await inSession(Request.findOneAndUpdate({_id:current._id,patient_id:patientId,status:current.status,workflowVersion:current.workflowVersion},{$set:{status:S.CANCELLED,'dispatch.status':DS.CLOSED,cancelled_at:new Date(),cancelled_by_user_id:new mongoose.Types.ObjectId(actor.user_id),cancellation_actor_type:'PATIENT',cancellation_reason:clean(reason,1000)},$inc:{workflowVersion:1,'dispatch.version':1}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw stale();await this.appendHistory(updated,Event.CANCELLED,actor,current.status,S.CANCELLED,previousPharmacyId,previousPharmacyId,reason,{quotation:this.quoteSnapshot(current.quotation)},session);if(previousPharmacyId)await domainNotificationService.pharmacy(updated,'cancelled',[previousPharmacyId],session!,'pharmacies');return updated;});
        await this.audit(result,actor,'PATCH',{reason});return result;
    }

    async adminAssign(id:string,pharmacyId:string,reason:string|undefined,actor:RxActor,overrideExclusion=false){
        const pharmacy=await pharmacyService.requireAssignable(pharmacyId);
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findById(oid(id)) as any,session).exec();if(!current)throw new DomainError('الطلب غير موجود',404,'PHARMACY_REQUEST_NOT_FOUND');assertPharmacyTransition(Op.ASSIGN,'ADMIN',current.status);const excluded=current.excluded_pharmacy_ids.some((value:any)=>String(value)===pharmacyId);if(excluded&&(!overrideExclusion||!clean(reason,1000)))throw new DomainError('تجاوز استبعاد الصيدلية يتطلب موافقة صريحة وسبباً',400,'PHARMACY_EXCLUDED');const updated=await inSession(Request.findOneAndUpdate({_id:current._id,status:S.OPEN,workflowVersion:current.workflowVersion,...openFilter()},{$set:{status:S.UNDER_REVIEW,'dispatch.status':DS.CLAIMED,'dispatch.mode':Mode.ADMIN_DIRECT,'dispatch.pharmacy_id':pharmacy._id,'dispatch.assigned_at':new Date(),'dispatch.assigned_by_user_id':new mongoose.Types.ObjectId(actor.user_id)},$inc:{workflowVersion:1,'dispatch.version':1}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw new DomainError('تم استلام الطلب مسبقاً',409,'REQUEST_ALREADY_CLAIMED');await this.appendHistory(updated,Event.ASSIGNED,actor,S.OPEN,S.UNDER_REVIEW,null,pharmacy._id,reason,excluded?{exclusion_override:true}:null,session);await domainNotificationService.pharmacy(updated,'assigned',[pharmacy._id],session!,'patient_and_pharmacies');return updated;});
        await this.audit(result,actor,'PATCH',{pharmacy_id:pharmacyId,reason,overrideExclusion});return result;
    }

    async adminReset(kind:'reassign'|'unassign',id:string,pharmacyId:string|undefined,reason:string,actor:RxActor){
        const pharmacy=kind==='reassign'?await pharmacyService.requireAssignable(pharmacyId!):null;
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findById(oid(id)) as any,session).exec();if(!current||!current.dispatch.pharmacy_id)throw new DomainError('الطلب غير موجود أو غير معين',404,'PHARMACY_REQUEST_NOT_FOUND');assertPharmacyTransition(kind==='reassign'?Op.REASSIGN:Op.UNASSIGN,'ADMIN',current.status);if(!clean(reason,1000))throw new DomainError('السبب مطلوب',400,'REASON_REQUIRED');if(pharmacy&&String(pharmacy._id)===String(current.dispatch.pharmacy_id))throw new DomainError('الصيدلية هي الصيدلية الحالية',409,'INVALID_STATE_TRANSITION');const set:any={quotation:null,status:kind==='reassign'?S.UNDER_REVIEW:S.OPEN,'dispatch.status':kind==='reassign'?DS.CLAIMED:DS.OPEN,'dispatch.mode':kind==='reassign'?Mode.ADMIN_REASSIGN:Mode.OPEN_POOL,'dispatch.pharmacy_id':pharmacy?._id??null,'dispatch.assigned_at':pharmacy?new Date():null,'dispatch.assigned_by_user_id':pharmacy?new mongoose.Types.ObjectId(actor.user_id):null};const updated=await inSession(Request.findOneAndUpdate({_id:current._id,status:current.status,workflowVersion:current.workflowVersion,'dispatch.pharmacy_id':current.dispatch.pharmacy_id,'dispatch.version':current.dispatch.version},{$set:set,$inc:{workflowVersion:1,'dispatch.version':1},$addToSet:{excluded_pharmacy_ids:current.dispatch.pharmacy_id}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw stale();await this.appendHistory(updated,kind==='reassign'?Event.REASSIGNED:Event.UNASSIGNED,actor,current.status,updated.status,current.dispatch.pharmacy_id,pharmacy?._id??null,reason,{quotation:this.quoteSnapshot(current.quotation)},session);await domainNotificationService.pharmacy(updated,kind==='reassign'?'reassigned':'unassigned',pharmacy?[pharmacy._id]:[],session!,kind==='reassign'?'patient_and_pharmacies':'patient');return updated;});
        await this.audit(result,actor,'PATCH',{pharmacy_id:pharmacyId,reason});return result;
    }

    async adminCancel(id:string,reason:string,actor:RxActor){
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findById(oid(id)) as any,session).exec();if(!current)throw new DomainError('الطلب غير موجود',404,'PHARMACY_REQUEST_NOT_FOUND');const previousPharmacyId=current.dispatch.pharmacy_id;assertPharmacyTransition(Op.ADMIN_CANCEL,'ADMIN',current.status);if(previousPharmacyId&&!clean(reason,1000))throw new DomainError('سبب الإلغاء مطلوب',400,'REASON_REQUIRED');const updated=await inSession(Request.findOneAndUpdate({_id:current._id,status:current.status,workflowVersion:current.workflowVersion},{$set:{status:S.CANCELLED,'dispatch.status':DS.CLOSED,cancelled_at:new Date(),cancelled_by_user_id:new mongoose.Types.ObjectId(actor.user_id),cancellation_actor_type:'ADMIN',cancellation_reason:clean(reason,1000)},$inc:{workflowVersion:1,'dispatch.version':1}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw stale();await this.appendHistory(updated,Event.CANCELLED,actor,current.status,S.CANCELLED,previousPharmacyId,previousPharmacyId,reason,{quotation:this.quoteSnapshot(current.quotation)},session);await domainNotificationService.pharmacy(updated,'cancelled',previousPharmacyId?[previousPharmacyId]:[],session!,'patient_and_pharmacies');return updated;});
        await this.audit(result,actor,'PATCH',{reason});return result;
    }

    async reopen(id:string,reason:string,actor:RxActor){
        const result=await this.transactions.run(async session=>{const current=await inSession(Request.findById(oid(id)) as any,session).exec();if(!current)throw new DomainError('الطلب غير موجود',404,'PHARMACY_REQUEST_NOT_FOUND');assertPharmacyTransition(Op.REOPEN,'ADMIN',current.status);if(!clean(reason,1000))throw new DomainError('سبب إعادة الفتح مطلوب',400,'REASON_REQUIRED');const updated=await inSession(Request.findOneAndUpdate({_id:current._id,status:current.status,workflowVersion:current.workflowVersion},{$set:{status:S.OPEN,quotation:null,'dispatch.status':DS.OPEN,'dispatch.mode':Mode.OPEN_POOL,'dispatch.pharmacy_id':null,'dispatch.assigned_at':null,'dispatch.assigned_by_user_id':null,cancelled_at:null,cancelled_by_user_id:null,cancellation_actor_type:null,cancellation_reason:null},$inc:{workflowVersion:1,'dispatch.version':1}},{returnDocument:'after',runValidators:true}) as any,session).exec();if(!updated)throw stale();await this.appendHistory(updated,Event.REOPENED,actor,current.status,S.OPEN,current.dispatch.pharmacy_id,null,reason,{quotation:this.quoteSnapshot(current.quotation)},session);await domainNotificationService.pharmacy(updated,'reopened',[],session!,'patient');return updated;});
        await this.audit(result,actor,'PATCH',{reason});return result;
    }

    async history(id:string,q:ListQuery={}){if(!mongoose.Types.ObjectId.isValid(id))return{data:[],count:0,page:1,limit:20};const page=Math.max(1,Number(q.page)||1),limit=Math.min(100,Math.max(1,Number(q.limit)||20));const filter={request_id:id};const[data,count]=await Promise.all([History.find(filter).sort({createdAt:1,_id:1}).skip((page-1)*limit).limit(limit).exec(),History.countDocuments(filter).exec()]);return{data,count,page,limit};}
    async adminList(q:ListQuery){const filter:any={};if(q.status)filter.status=q.status;if(q.payment_method)filter.preferred_payment_method=q.payment_method;if(q.dispatch_mode)filter['dispatch.mode']=q.dispatch_mode;if(q.has_quotation!==undefined)filter.quotation=q.has_quotation==='true'?{$ne:null}:null;for(const key of ['pharmacy_id','patient_id'])if(q[key])filter[key==='pharmacy_id'?'dispatch.pharmacy_id':key]=oid(String(q[key]));if(q.request_number)filter.request_number=String(q.request_number).trim();if(q.search){const search=safeSearchPattern(String(q.search));filter.$or=['request_number','treatment_details','delivery_address.address_text','delivery_phone'].map(key=>({[key]:{$regex:search,$options:'i'}}))}return this.list(filter,q);}
    async adminGet(id:string){if(!mongoose.Types.ObjectId.isValid(id))return null;return populated(Request.findById(id)).exec();}

    private async list(filter:FilterQuery<IPharmacyTreatmentRequest>,q:ListQuery,available=false){const page=Math.max(1,Number(q.page)||1),limit=Math.min(100,Math.max(1,Number(q.limit)||10));if(q.status)filter.status=q.status;if(q.dateFrom||q.dateTo){const range:any={};if(q.dateFrom){const date=new Date(q.dateFrom);if(Number.isNaN(date.getTime()))throw new DomainError('تاريخ البداية غير صالح',400,'INVALID_DATE_RANGE');range.$gte=date;}if(q.dateTo){const date=new Date(q.dateTo);if(Number.isNaN(date.getTime()))throw new DomainError('تاريخ النهاية غير صالح',400,'INVALID_DATE_RANGE');range.$lte=date;}filter.createdAt=range;}const[data,count]=await Promise.all([populated(Request.find(filter)).sort(available?{createdAt:1,_id:1}:{createdAt:-1,_id:-1}).skip((page-1)*limit).limit(limit).exec(),Request.countDocuments(filter).exec()]);return{data,count,page,limit};}
    private quoteSnapshot(quotation:any,accepted=false){if(!quotation)return null;return{version:quotation.version,pharmacy_id:quotation.pharmacy_id,items:quotation.items.map((item:any)=>({name:item.name,quantity:item.quantity,unit_price:item.unit_price,line_total:item.line_total,note:item.note??null})),unavailable_items:quotation.unavailable_items.map((item:any)=>({name:item.name,note:item.note??null})),medicines_subtotal:quotation.medicines_subtotal,delivery_fee:quotation.delivery_fee,discount:quotation.discount,total_price:quotation.total_price,pharmacy_note:quotation.pharmacy_note??null,quoted_at:quotation.quoted_at,accepted_at:accepted?quotation.accepted_at??null:quotation.accepted_at??null};}
    private lifecycleOperation(expected:PharmacyRequestStatus,next:PharmacyRequestStatus):PharmacyWorkflowOperation{const key=`${expected}:${next}`;const operations:Record<string,PharmacyWorkflowOperation>={[`${S.CONFIRMED}:${S.PREPARING}`]:Op.START_PREPARING,[`${S.PREPARING}:${S.READY_FOR_DELIVERY}`]:Op.MARK_READY,[`${S.READY_FOR_DELIVERY}:${S.OUT_FOR_DELIVERY}`]:Op.START_DELIVERY,[`${S.OUT_FOR_DELIVERY}:${S.DELIVERED}`]:Op.DELIVER};const operation=operations[key];if(!operation)throw new DomainError('لا يمكن تنفيذ هذا الإجراء في حالة الطلب الحالية',409,'INVALID_STATE_TRANSITION');return operation;}
    private async appendHistory(request:any,event_type:string,actor:RxActor,from_status:any,to_status:any,from_pharmacy:any=null,to_pharmacy:any=null,reason:any=null,metadata:any=null,session:ClientSession|null=null){const entry={request_id:request._id,request_number:request.request_number,event_type,actor:{type:actor.type,user_id:actor.user_id?new mongoose.Types.ObjectId(actor.user_id):null,pharmacy_id:actor.pharmacy_id?new mongoose.Types.ObjectId(actor.pharmacy_id):null},from_status,to_status,from_pharmacy_id:from_pharmacy,to_pharmacy_id:to_pharmacy,quotation_version:request.quotation?.version??metadata?.quotation?.version??null,total_price:request.quotation?.total_price??metadata?.quotation?.total_price??null,reason:clean(reason,1000),metadata};await this.historyWriter.create([entry],session?{session}:{});}
    private async audit(request:any,actor:RxActor,method:string,body:any){try{const raw=request.toObject?.()??request;const{prescription_images,treatment_details,delivery_address,delivery_phone,notes,...safeRequest}=raw;let safeBody=body;if(body&&typeof body==='object'){const{prescription_images:_images,treatment_details:_details,delivery_address:_address,delivery_phone:_phone,notes:_notes,...operationalBody}=body;safeBody=operationalBody;}await ActivityLogService.logActivity({user_id:actor.user_id,user_name:`${actor.type.toLowerCase()}_${actor.user_id}`,user_type:actor.type.toLowerCase(),method,endpoint:actor.endpoint,action:IActivityLogActionEnum.UPDATE,collection_name:'pharmacy_treatment_requests',document_id:String(request._id),new_data:{...safeRequest,prescription_image_count:Array.isArray(prescription_images)?prescription_images.length:0},request_body:safeBody,source:actor.type==='PATIENT'?IActivityLogSourceEnum.MOBILE:IActivityLogSourceEnum.DASHBOARD});}catch(error){console.error('[WARN] Pharmacy request ActivityLog write failed',error);}}
}

export default new PharmacyTreatmentRequestService();
