import mongoose,{type FilterQuery} from 'mongoose'; import Pharmacy,{type PharmacyDocument} from '../models/pharmacy.model'; import User from '../models/users.model'; import {IPharmacyStatusEnum,type IPharmacy,type IPharmacyStatus} from '../interfaces/pharmacy.interface'; import {IUserRoleEnum,IUserStatusEnum} from '../interfaces/user.interface'; import {hashPassword} from '../constants/hashing'; import {DomainError} from './domain-error'; import ActivityLogService from './activity-log.service'; import {IActivityLogActionEnum,IActivityLogSourceEnum} from '../interfaces/activity-log.interface'; import sessionService from './session.service'; import uploadPolicyService from './upload-policy.service'; import {UploadPurposeEnum} from '../constants/upload-policy';
export interface PharmacyCreateInput{name:string;display_name?:string|null;phone:string;password:string;email?:string|null;logo?:string|null;license_number?:string|null;license_verified?:boolean;address:{address_text:string;lat?:number|null;lng?:number|null};accepts_prescription_requests?:boolean}
export class PharmacyService{
 async getById(id:string){if(!mongoose.Types.ObjectId.isValid(id))return null;return Pharmacy.findById(id).exec()}
 async getByUserId(id:string){if(!mongoose.Types.ObjectId.isValid(id))return null;return Pharmacy.findOne({user_id:id}).exec()}
 async requireOperational(userId:string){const[p,user]=await Promise.all([this.getByUserId(userId),User.findOne({_id:userId,role:IUserRoleEnum.PHARMACY,status:IUserStatusEnum.ACTIVE}).select('_id').exec()]);if(!p)throw new DomainError('الملف الشخصي للصيدلية غير موجود',404,'PHARMACY_NOT_FOUND');if(!user||p.status!==IPharmacyStatusEnum.ACTIVE||!p.accepts_prescription_requests)throw new DomainError('الصيدلية غير متاحة لاستقبال الطلبات',403,'PHARMACY_NOT_ELIGIBLE');return p}
 async requireAssignable(id:string){const p=await this.getById(id);if(!p)throw new DomainError('الصيدلية غير موجودة أو غير فعالة',404,'PHARMACY_NOT_ELIGIBLE');const user=await User.findOne({_id:p.user_id,role:IUserRoleEnum.PHARMACY,status:IUserStatusEnum.ACTIVE}).select('_id').exec();if(!user||p.status!==IPharmacyStatusEnum.ACTIVE||!p.accepts_prescription_requests)throw new DomainError('الصيدلية غير موجودة أو غير فعالة',404,'PHARMACY_NOT_ELIGIBLE');return p}
 async list(q:{page?:number;limit?:number;status?:IPharmacyStatus;accepts?:boolean;search?:string}){const page=Math.max(1,q.page??1),limit=Math.min(100,Math.max(1,q.limit??10));const f:FilterQuery<IPharmacy>={};if(q.status)f.status=q.status;if(q.accepts!==undefined)f.accepts_prescription_requests=q.accepts;if(q.search?.trim())f.$or=['name','display_name','phone','license_number'].map(k=>({[k]:{$regex:q.search!.trim(),$options:'i'}}));const[data,count]=await Promise.all([Pharmacy.find(f).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).exec(),Pharmacy.countDocuments(f).exec()]);return{data,count}}
 async createAccount(input:PharmacyCreateInput,adminId:string){if(input.logo)throw new DomainError('أنشئ ملف الصيدلية ثم ارفع شعارها لغرضه المحدد',422,'UPLOAD_TARGET_NOT_FOUND');if(await User.findOne({phone:input.phone}).exec())throw new DomainError('رقم الهاتف مستخدم مسبقاً',409);const password_hash=await hashPassword(input.password);let user:any=null;try{user=await User.create({full_name:input.name,email:input.email??undefined,phone:input.phone,password_hash,role:IUserRoleEnum.PHARMACY,status:IUserStatusEnum.ACTIVE,is_phone_verified:false,is_email_verified:false});const p=await Pharmacy.create({user_id:user._id,name:input.name,display_name:input.display_name??input.name,phone:input.phone,logo:null,license_number:input.license_number??null,license_verified:input.license_verified??false,address:input.address,accepts_prescription_requests:input.accepts_prescription_requests??true,status:IPharmacyStatusEnum.ACTIVE});const{password:_,...safeInput}=input;await this.audit(p,null,safeInput,adminId,'POST','/dash/admin/pharmacies');return p}catch(e){if(user?._id)await User.findByIdAndDelete(user._id).exec();throw e}}
 async update(id:string,input:Partial<IPharmacy>,adminId:string,endpoint:string){const old=await this.getById(id);if(!old)throw new DomainError('الصيدلية غير موجودة',404);const media=input.logo?await uploadPolicyService.requireReadyReference(input.logo,UploadPurposeEnum.PHARMACY_LOGO,'PHARMACY',id):null;if(input.status!==undefined&&input.status!==IPharmacyStatusEnum.ACTIVE&&input.status!==old.status)await sessionService.revokeAll(String(old.user_id),{reasonCode:'PHARMACY_STATUS_DISABLED'});const p=await Pharmacy.findByIdAndUpdate(id,{$set:input},{returnDocument:'after',runValidators:true}).exec();if(!p)throw new DomainError('الصيدلية غير موجودة',404);if(input.logo!==undefined)await uploadPolicyService.finalizeReplacement(media,old.logo,id,'logo');await this.audit(p,old,input,adminId,'PATCH',endpoint);return p}
 private async audit(p:PharmacyDocument,old:PharmacyDocument|null,body:unknown,adminId:string,method:string,endpoint:string){try{await ActivityLogService.logActivity({user_id:adminId,user_name:`admin_${adminId}`,user_type:'admin',method,endpoint,action:old?IActivityLogActionEnum.UPDATE:IActivityLogActionEnum.CREATE,collection_name:'pharmacies',document_id:String(p._id),old_data:old?.toObject?.()??old,new_data:p.toObject?.()??p,request_body:body,source:IActivityLogSourceEnum.DASHBOARD})}catch(error){console.error('[WARN] Pharmacy ActivityLog write failed',error)}}
}
export default new PharmacyService();
