import Elysia, { t } from 'elysia';
import { AuthPlugin } from '../../../middleware/auth.middleware';
import { SWAGGER_TAGS } from '../../../constants/swagger-tags';
import doctorService from '../../../services/doctor.service';
import appointmentService, { formatAppointment } from '../../../services/appointment.service';
import appointmentSlotService from '../../../services/appointment-slot.service';
import appointmentWorkflowService from '../../../services/appointment-workflow.service';
import doctorAvailabilityService from '../../../services/doctor-availability.service';
import { AppointmentActorTypeEnum, IAppointmentStatusEnum } from '../../../interfaces/appointment.interface';
import { DomainError } from '../../../services/domain-error';
import { AppointmentCalendarResponseSchema, AppointmentListResponseSchema, AppointmentResponseSchema, AvailabilityListResponseSchema, BookingSettingsResponseSchema, ExceptionBodySchema, ExceptionListResponseSchema, ExceptionResponseSchema, HistoryResponseSchema, SettingsBodySchema, SlotsResponseSchema, WeeklyDaySchema } from '../../../schemas/appointment-response.schema';
import { BadRequestResponseSchema, ConflictResponseSchema, ForbiddenResponseSchema, NotFoundResponseSchema, ProtectedApiErrorResponses, SuccessResponseWithoutDataSchema, ValidationOrBusinessRuleResponseSchema } from '../../../schemas/api-response.schema';

const errors = { 400: BadRequestResponseSchema, 403: ForbiddenResponseSchema, 404: NotFoundResponseSchema, 409: ConflictResponseSchema, 422: ValidationOrBusinessRuleResponseSchema, ...ProtectedApiErrorResponses };
const destinationSchema = t.Object({ doctorId: t.Optional(t.String()), clinicId: t.Optional(t.String()), specialtyId: t.Optional(t.Nullable(t.String())), date: t.String({ format: 'date' }), startsAt: t.String({ format: 'date-time' }), reason: t.Optional(t.Nullable(t.String({ maxLength: 1000 }))) }, { additionalProperties: false });
const pagination = (page: number, limit: number, total: number) => ({ page, limit, total, pages: Math.ceil(total / limit), hasNext: page * limit < total, hasPrev: page > 1 });
async function self(userId: string) { const doctor = await doctorService.getByUserId(userId); if (!doctor) throw new DomainError('الملف الشخصي غير موجود', 404, 'DOCTOR_NOT_BOOKABLE'); return doctor; }
const actor = (userId: string, doctorId: string) => ({ type: AppointmentActorTypeEnum.DOCTOR, userId, doctorId });

export const doctorAppointmentsController = new Elysia({ prefix: '/appointments', detail: { tags: [SWAGGER_TAGS.DOCTOR.APPOINTMENTS] } })
    .use(AuthPlugin())
    .onError(({ error, set }) => { if (error instanceof DomainError) { set.status = error.status; return { error: true, message: error.message, code: error.code }; } })
    .get('/availability/weekly/:clinicId', async ({ params, phrase }) => { const doctor = await self(phrase._id); return { error: false, message: 'تم جلب جدول الدوام', data: await doctorAvailabilityService.weekly(String(doctor._id), params.clinicId) }; }, { response: { 200: AvailabilityListResponseSchema, ...errors } })
    .put('/availability/weekly/:clinicId', async ({ params, body, phrase }) => { const doctor = await self(phrase._id); return { error: false, message: 'تم تحديث جدول الدوام', data: await doctorAvailabilityService.replaceWeekly(String(doctor._id), params.clinicId, body.days, actor(phrase._id, String(doctor._id))) }; }, { body: t.Object({ days: t.Array(WeeklyDaySchema, { maxItems: 7 }) }, { additionalProperties: false }), response: { 200: AvailabilityListResponseSchema, ...errors } })
    .get('/availability/exceptions', async ({ query, phrase }) => { const doctor = await self(phrase._id); return { error: false, message: 'تم جلب استثناءات الدوام', data: await doctorAvailabilityService.exceptions(String(doctor._id), query.from, query.to) }; }, { query: t.Object({ from: t.Optional(t.String({ format: 'date' })), to: t.Optional(t.String({ format: 'date' })) }), response: { 200: ExceptionListResponseSchema, ...errors } })
    .post('/availability/exceptions', async ({ body, phrase, set }) => { const doctor = await self(phrase._id); const data = await doctorAvailabilityService.createException(String(doctor._id), body, actor(phrase._id, String(doctor._id))); set.status = 201; return { error: false, message: 'تم إنشاء استثناء الدوام', data }; }, { body: ExceptionBodySchema, response: { 201: ExceptionResponseSchema, ...errors } })
    .patch('/availability/exceptions/:id', async ({ params, body, phrase }) => { const doctor = await self(phrase._id); return { error: false, message: 'تم تحديث استثناء الدوام', data: await doctorAvailabilityService.updateException(String(doctor._id), params.id, body, actor(phrase._id, String(doctor._id))) }; }, { body: t.Partial(ExceptionBodySchema), response: { 200: ExceptionResponseSchema, ...errors } })
    .delete('/availability/exceptions/:id', async ({ params, phrase }) => { const doctor = await self(phrase._id); await doctorAvailabilityService.deleteException(String(doctor._id), params.id, actor(phrase._id, String(doctor._id))); return { error: false, message: 'تم حذف استثناء الدوام' }; }, { response: { 200: SuccessResponseWithoutDataSchema, ...errors } })
    .get('/availability/preview', async ({ query, phrase }) => { const doctor = await self(phrase._id); const result = await appointmentSlotService.getSlots({ doctorId: String(doctor._id), clinicId: query.clinicId, specialtyId: query.specialtyId, date: query.date }, { enforceLeadTime: false }); return { error: false, message: 'تم جلب معاينة الأوقات', data: { doctorId: result.doctorId, clinicId: result.clinicId, date: result.date, timezone: result.timezone, slots: result.slots } }; }, { query: t.Object({ clinicId: t.String(), specialtyId: t.Optional(t.String()), date: t.String({ format: 'date' }) }), response: { 200: SlotsResponseSchema, ...errors } })
    .patch('/availability/settings', async ({ body, phrase }) => { const doctor = await self(phrase._id); return { error: false, message: 'تم تحديث إعدادات الحجز', data: await doctorAvailabilityService.updateSettings(String(doctor._id), body, actor(phrase._id, String(doctor._id))) }; }, { body: SettingsBodySchema, response: { 200: BookingSettingsResponseSchema, ...errors } })
    .get('/calendar', async ({ query, phrase }) => { const doctor = await self(phrase._id); const result = await appointmentService.list({ doctorId: String(doctor._id), from: new Date(query.from), to: new Date(query.to), clinicId: query.clinicId, status: query.status, limit: 100 }); return { error: false, message: 'تم جلب تقويم المواعيد', data: result.data.map(item => formatAppointment(item, { includeInternal: true })) }; }, { query: t.Object({ from: t.String({ format: 'date-time' }), to: t.String({ format: 'date-time' }), clinicId: t.Optional(t.String()), status: t.Optional(t.Enum(IAppointmentStatusEnum)) }), response: { 200: AppointmentCalendarResponseSchema, ...errors } })
    .get('/', async ({ query, phrase }) => { const doctor = await self(phrase._id); const result = await appointmentService.list({ doctorId: String(doctor._id), page: Number(query.page) || 1, limit: Number(query.limit) || 20, clinicId: query.clinicId, patientId: query.patientId, status: query.status, from: query.from ? new Date(query.from) : undefined, to: query.to ? new Date(query.to) : undefined, search: query.search }); return { error: false, message: 'تم جلب المواعيد', data: result.data.map(item => formatAppointment(item, { includeInternal: true })), pagination: pagination(result.page, result.limit, result.count) }; }, { query: t.Object({ page: t.Optional(t.String()), limit: t.Optional(t.String()), clinicId: t.Optional(t.String()), patientId: t.Optional(t.String()), status: t.Optional(t.Enum(IAppointmentStatusEnum)), from: t.Optional(t.String({ format: 'date-time' })), to: t.Optional(t.String({ format: 'date-time' })), search: t.Optional(t.String()) }), response: { 200: AppointmentListResponseSchema, ...errors } })
    .get('/:id', async ({ params, phrase }) => { const doctor = await self(phrase._id), appointment = await appointmentService.doctorAppointment(params.id, String(doctor._id)); return { error: false, message: 'تم جلب الموعد', data: formatAppointment(appointment, { includeInternal: true }) }; }, { response: { 200: AppointmentResponseSchema, ...errors } })
    .get('/:id/history', async ({ params, phrase }) => { const doctor = await self(phrase._id); await appointmentService.doctorAppointment(params.id, String(doctor._id)); return { error: false, message: 'تم جلب سجل الموعد', data: await appointmentService.history(params.id) }; }, { response: { 200: HistoryResponseSchema, ...errors } })
    .post('/:id/confirm', ({ params, phrase }) => operation(params.id, phrase, 'confirm'), { response: { 200: AppointmentResponseSchema, ...errors } })
    .post('/:id/check-in', ({ params, phrase }) => operation(params.id, phrase, 'checkIn'), { response: { 200: AppointmentResponseSchema, ...errors } })
    .post('/:id/start', ({ params, phrase }) => operation(params.id, phrase, 'start'), { response: { 200: AppointmentResponseSchema, ...errors } })
    .post('/:id/complete', ({ params, phrase }) => operation(params.id, phrase, 'complete'), { response: { 200: AppointmentResponseSchema, ...errors } })
    .post('/:id/no-show', ({ params, phrase }) => operation(params.id, phrase, 'noShow'), { response: { 200: AppointmentResponseSchema, ...errors } })
    .post('/:id/cancel', async ({ params, body, phrase }) => { const doctor = await self(phrase._id), result = await appointmentWorkflowService.cancel(params.id, actor(phrase._id, String(doctor._id)), body.reason); return { error: false, message: 'تم إلغاء الموعد', data: formatAppointment(result, { includeInternal: true }) }; }, { body: t.Object({ reason: t.Optional(t.Nullable(t.String({ maxLength: 1000 }))) }), response: { 200: AppointmentResponseSchema, ...errors } })
    .post('/:id/reschedule', async ({ params, body, phrase }) => { const doctor = await self(phrase._id), result = await appointmentWorkflowService.reschedule(params.id, body, actor(phrase._id, String(doctor._id))); return { error: false, message: 'تمت إعادة جدولة الموعد', data: formatAppointment(result.appointment, { includeInternal: true }) }; }, { body: destinationSchema, response: { 200: AppointmentResponseSchema, ...errors } })
    .patch('/:id/notes', async ({ params, body, phrase }) => { const doctor = await self(phrase._id), result = await appointmentWorkflowService.updateInternalNotes(params.id, body.notesInternal ?? null, actor(phrase._id, String(doctor._id))); return { error: false, message: 'تم تحديث الملاحظات', data: formatAppointment(result, { includeInternal: true }) }; }, { body: t.Object({ notesInternal: t.Optional(t.Nullable(t.String({ maxLength: 2000 }))) }, { additionalProperties: false }), response: { 200: AppointmentResponseSchema, ...errors } });

async function operation(id: string, phrase: { _id: string }, action: 'confirm' | 'checkIn' | 'start' | 'complete' | 'noShow') {
    const doctor = await self(phrase._id); const result = await appointmentWorkflowService[action](id, actor(phrase._id, String(doctor._id)));
    return { error: false, message: 'تم تحديث حالة الموعد', data: formatAppointment(result, { includeInternal: true }) };
}
