import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, mock, spyOn, test } from 'bun:test';
import mongoose from 'mongoose';
import User from '../src/models/users.model'; import Patient from '../src/models/patients.model'; import Nurse from '../src/models/nurse.model'; import Pharmacy from '../src/models/pharmacy.model';
import HomeCareCategory from '../src/models/home-care-category.model'; import HomeCareService from '../src/models/home-care-service.model'; import HomeCareRequest from '../src/models/home-care-request.model'; import HomeCareRequestHistory from '../src/models/home-care-request-history.model'; import HomeCareRequestCounter from '../src/models/home-care-request-counter.model';
import Notification from '../src/models/notifications.model'; import NotificationRecipient from '../src/models/notification-recipient.model'; import NotificationDelivery from '../src/models/notification-delivery.model';
import PharmacyRequest from '../src/models/pharmacy-treatment-request.model'; import PharmacyHistory from '../src/models/pharmacy-treatment-request-history.model'; import PharmacyCounter from '../src/models/pharmacy-treatment-request-counter.model';
import domainNotificationService from '../src/services/domain-notification.service'; import { HomeCareRequestService } from '../src/services/home-care-request.service'; import { HomeCareDispatchService } from '../src/services/home-care-dispatch.service'; import { PharmacyTreatmentRequestService } from '../src/services/pharmacy-treatment-request.service';
import { IHomeCareDispatchModeEnum as Mode, IHomeCareDispatchStatusEnum as Dispatch, IHomeCareRequestStatusEnum as Status } from '../src/interfaces/home-care-request.interface'; import { PharmacyRequestStatusEnum as PharmacyStatus } from '../src/interfaces/pharmacy-treatment-request.interface'; import { INotificationTypeEnum as Type } from '../src/interfaces/notification.interface';

const uri = process.env.MONGODB_TEST_URI; const run = uri ? describe : describe.skip;
const requests = new HomeCareRequestService(), dispatch = new HomeCareDispatchService();
run('Phase 8C Home Care durable notifications against MongoDB rs0', () => {
    const dbName = `cannula_notification_phase8c_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    let patient: any, patientB: any, admin: any, nurseA: any, nurseB: any, care: any, serial = 0;
    const patientActor = () => ({ user_id: String(patient.user_id), user_type: 'patient' as const, endpoint: '/mobile/test', source: 'mobile' as const });
    const adminActor = () => ({ user_id: String(admin._id), user_type: 'admin' as const, endpoint: '/admin/test', source: 'dashboard' as const });
    const nurseActor = (nurse: any) => ({ user_id: String(nurse.user_id), user_type: 'nurse' as const, nurse_id: String(nurse._id), endpoint: '/nurse/test' });
    const rejected = async (p: Promise<unknown>) => { try { await p; } catch (error) { return error; } throw new Error('Expected rejection'); };
    beforeAll(async () => { await mongoose.connect(uri!, { dbName }); const s = await mongoose.startSession(); try { await s.withTransaction(async () => undefined); } finally { await s.endSession(); } await Promise.all([User.syncIndexes(), Patient.syncIndexes(), Nurse.syncIndexes(), HomeCareCategory.syncIndexes(), HomeCareService.syncIndexes(), HomeCareRequest.syncIndexes(), HomeCareRequestHistory.syncIndexes(), Notification.syncIndexes(), NotificationRecipient.syncIndexes(), NotificationDelivery.syncIndexes()]); });
    afterAll(async () => { if (mongoose.connection.db) await mongoose.connection.db.dropDatabase(); await mongoose.disconnect(); }); afterEach(() => mock.restore());
    beforeEach(async () => { await Promise.all([User.deleteMany({}), Patient.deleteMany({}), Nurse.deleteMany({}), HomeCareCategory.deleteMany({}), HomeCareService.deleteMany({}), HomeCareRequest.deleteMany({}), HomeCareRequestHistory.deleteMany({}), HomeCareRequestCounter.deleteMany({}), Notification.deleteMany({}), NotificationRecipient.deleteMany({}), NotificationDelivery.deleteMany({})]); const users = await User.create(['Patient','Patient B','Admin','Nurse A','Nurse B'].map((full_name, i) => ({ full_name, phone: `079${Date.now()}${i}`, password_hash: 'hash', role: i < 2 ? 'patient' : i === 2 ? 'admin' : 'nurse', status: 'active', is_phone_verified: true }))); patient = await Patient.create({ user_id: users[0]._id, full_name: 'Patient', phone: users[0].phone, status: 'active' }); patientB = await Patient.create({ user_id: users[1]._id, full_name: 'Patient B', phone: users[1].phone, status: 'active' }); admin = users[2]; const category = await HomeCareCategory.create({ name: `Category ${Date.now()}`, normalized_name: `category-${Date.now()}`, status: 'active' }); care = await HomeCareService.create({ category_id: category._id, name: `Care ${Date.now()}`, price: 10000, status: 'active' }); nurseA = await Nurse.create({ user_id: users[3]._id, full_name: 'Nurse A', status: 'active', qualified_service_ids: [care._id] }); nurseB = await Nurse.create({ user_id: users[4]._id, full_name: 'Nurse B', status: 'active', qualified_service_ids: [care._id] }); });
    async function request(status: string = Status.PENDING, nurse: any = null, version = 0) { serial += 1; return HomeCareRequest.create({ request_number: `HC-8C-${serial}`, patient_id: patient._id, category_id: care.category_id, service_id: care._id, service_name: care.name, service_price: care.price, requested_date: new Date('2099-01-02'), preferred_time: '12:00', address: { address_text: 'Baghdad test', lat: 33.3, lng: 44.3 }, status, dispatch: { status: nurse ? Dispatch.CLAIMED : Dispatch.OPEN, mode: nurse ? Mode.ADMIN_DIRECT : Mode.OPEN_POOL, nurse_id: nurse?._id ?? null, assigned_at: nurse ? new Date() : null, assigned_by_user_id: nurse ? admin._id : null, version }, cancelled_at: null, cancelled_by: null, cancellation_reason: null }); }
    async function notifications(item: any, type: string) { return Notification.find({ 'source.id': item._id, type }).lean(); }
    async function recipients(items: any[]) { return NotificationRecipient.find({ notification_id: { $in: items.map(x => x._id) } }).lean(); }
    async function assertDeliveries(items: any[], users: any[]) { expect(await NotificationDelivery.countDocuments({ notification_id: { $in: items.map(x => x._id) }, user_id: { $in: users } })).toBe(users.length); }
    async function assertRecipientIds(items: any[], expected: any[]) { const rows = await recipients(items); expect(rows.map(x => String(x.user_id)).sort()).toEqual(expected.map(String).sort()); await assertDeliveries(items, expected); }

    test('CONFIRMED targets only canonical Patient User with sensitive durable event and cross-user isolation', async () => { const item = await request(); await requests.updateStatus(String(item._id), Status.CONFIRMED, adminActor()); const rows = await notifications(item, Type.HOME_CARE_CONFIRMED); expect(rows).toHaveLength(1); expect(rows[0]).toMatchObject({ category: 'services', privacy: 'sensitive', source: { domain: 'home_care_request' }, target: { type: 'home_care_request' } }); expect(JSON.stringify(rows[0])).not.toMatch(/icon_url|background_color|badge_color|"icon"|"color"/); await assertRecipientIds(rows, [patient.user_id]); expect(String((await recipients(rows))[0].user_id)).not.toBe(String(patient._id)); expect(await NotificationRecipient.countDocuments({ notification_id: rows[0]._id, user_id: patientB.user_id })).toBe(0); });
    test('nurse claim notifies Patient only; direct assignment notifies Patient and Nurse canonical Users', async () => { const claimed = await request(); await dispatch.claim(String(nurseA.user_id), String(claimed._id), nurseActor(nurseA)); const claimRows = await notifications(claimed, Type.HOME_CARE_ASSIGNED); await assertRecipientIds(claimRows, [patient.user_id]); const assigned = await request(); await dispatch.assign(String(assigned._id), String(nurseA._id), adminActor()); const assignRows = await notifications(assigned, Type.HOME_CARE_ASSIGNED); await assertRecipientIds(assignRows, [patient.user_id, nurseA.user_id]); expect((await recipients(assignRows)).map(x => String(x.user_id))).not.toContain(String(nurseA._id)); });
    test('progression emits exactly one Patient event per transition and no Nurse self notification', async () => { const item = await request(Status.ASSIGNED, nurseA); for (const [from, to, type] of [[Status.ASSIGNED, Status.ON_THE_WAY, Type.HOME_CARE_ON_THE_WAY], [Status.ON_THE_WAY, Status.ARRIVED, Type.HOME_CARE_ARRIVED], [Status.ARRIVED, Status.IN_PROGRESS, Type.HOME_CARE_IN_PROGRESS], [Status.IN_PROGRESS, Status.COMPLETED, Type.HOME_CARE_COMPLETED]] as const) { await dispatch.transition(String(nurseA.user_id), String(item._id), from, to, nurseActor(nurseA)); const rows = await notifications(item, type); expect(rows).toHaveLength(1); await assertRecipientIds(rows, [patient.user_id]); } });
    test('reassign targets Patient and new Nurse; unassign targets Patient only', async () => { const item = await request(Status.ASSIGNED, nurseA); await dispatch.reassign(String(item._id), String(nurseB._id), 'reason', adminActor()); const reassign = await notifications(item, Type.HOME_CARE_ASSIGNED); await assertRecipientIds(reassign, [patient.user_id, nurseB.user_id]); expect((await recipients(reassign)).map(x => String(x.user_id))).not.toContain(String(nurseA.user_id)); await dispatch.unassign(String(item._id), 'reason', adminActor()); const reassignIds = new Set(reassign.map(x => String(x._id))); const unassigned = (await notifications(item, Type.HOME_CARE_ASSIGNED)).filter(x => !reassignIds.has(String(x._id))); await assertRecipientIds(unassigned, [patient.user_id]); });
    test('patient cancellation sends Nurse only when a cancellable request has an assigned Nurse, and no-nurse cancellation sends no event', async () => { const assigned = await request(Status.CONFIRMED, nurseA); await requests.cancelForPatient(patient._id, String(assigned._id), 'reason', patientActor()); const withNurse = await notifications(assigned, Type.HOME_CARE_CANCELLED); await assertRecipientIds(withNurse, [nurseA.user_id]); const open = await request(); await requests.cancelForPatient(patient._id, String(open._id), 'reason', patientActor()); expect(await notifications(open, Type.HOME_CARE_CANCELLED)).toHaveLength(0); });
    test('admin cancellation recipient matrix and rejection target Patient only', async () => { const assigned = await request(Status.ASSIGNED, nurseA); await requests.cancelForAdmin(String(assigned._id), 'reason', adminActor()); await assertRecipientIds(await notifications(assigned, Type.HOME_CARE_CANCELLED), [patient.user_id, nurseA.user_id]); const open = await request(); await requests.cancelForAdmin(String(open._id), 'reason', adminActor()); await assertRecipientIds(await notifications(open, Type.HOME_CARE_CANCELLED), [patient.user_id]); const rejectedRequest = await request(); await requests.rejectForAdmin(String(rejectedRequest._id), 'reason', adminActor()); await assertRecipientIds(await notifications(rejectedRequest, Type.HOME_CARE_REJECTED), [patient.user_id]); });
    test('dedupe is DB authoritative for the same request/version/event/user', async () => { const item = await request(); await requests.updateStatus(String(item._id), Status.CONFIRMED, adminActor()); const before = await Promise.all([Notification.countDocuments(), NotificationRecipient.countDocuments(), NotificationDelivery.countDocuments()]); const committed = await HomeCareRequest.findById(item._id); const session = await mongoose.startSession(); try { await domainNotificationService.homeCare(committed, 'confirmed', [], session, 'patient'); } finally { await session.endSession(); } expect(await Promise.all([Notification.countDocuments(), NotificationRecipient.countDocuments(), NotificationDelivery.countDocuments()])).toEqual(before); });
    test('post-notification throw rolls back request, history, notification, recipient, and delivery', async () => { const item = await request(); const original = domainNotificationService.homeCare; spyOn(domainNotificationService, 'homeCare').mockImplementation(async (...args: any[]) => { await (original as any).apply(domainNotificationService, args); throw new Error('FORCED_AFTER_NOTIFICATION_APPEND'); }); await rejected(requests.updateStatus(String(item._id), Status.CONFIRMED, adminActor())); const final = await HomeCareRequest.findById(item._id).lean(); expect(final?.status).toBe(Status.PENDING); expect(await HomeCareRequestHistory.countDocuments({ request_id: item._id })).toBe(0); expect(await Notification.countDocuments()).toBe(0); expect(await NotificationRecipient.countDocuments()).toBe(0); expect(await NotificationDelivery.countDocuments()).toBe(0); });
    test('real claim race has one winner, one durable notification bundle; failed transition creates none', async () => { const item = await request(); const outcomes = await Promise.allSettled([dispatch.claim(String(nurseA.user_id), String(item._id), nurseActor(nurseA)), dispatch.claim(String(nurseB.user_id), String(item._id), nurseActor(nurseB))]); expect(outcomes.filter(x => x.status === 'fulfilled')).toHaveLength(1); const rows = await notifications(item, Type.HOME_CARE_ASSIGNED); expect(rows).toHaveLength(1); await assertRecipientIds(rows, [patient.user_id]); const winner = await HomeCareRequest.findById(item._id).lean(); const winnerNurse = String(winner?.dispatch.nurse_id) === String(nurseA._id) ? nurseA : nurseB; const before = await Promise.all([Notification.countDocuments(), NotificationRecipient.countDocuments(), NotificationDelivery.countDocuments()]); await rejected(dispatch.transition(String(winnerNurse.user_id), String(item._id), Status.ON_THE_WAY, Status.ARRIVED, nurseActor(winnerNurse))); expect(await Promise.all([Notification.countDocuments(), NotificationRecipient.countDocuments(), NotificationDelivery.countDocuments()])).toEqual(before); });
});

run('Phase 8C Pharmacy durable notifications against MongoDB rs0', () => {
    const dbName = `cannula_p8c_rx_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    const service = new PharmacyTreatmentRequestService(); let patient: any, patientB: any, admin: any, pharmacyA: any, pharmacyB: any, sequence = 0;
    const actor = (user: any, type: 'PATIENT' | 'PHARMACY' | 'ADMIN') => ({ user_id: String(user._id ?? user), type, endpoint: '/phase8c' } as const);
    const quote = (price = 1000) => ({ items: [{ name: 'private medicine', quantity: 1, unit_price: price, note: 'private line note' }], unavailable_items: [{ name: 'private unavailable medicine' }], delivery_fee: 0, discount: 0, pharmacy_note: 'private pharmacy note' });
    const rejected = async (p: Promise<unknown>) => { try { await p; } catch (error) { return error; } throw new Error('Expected rejection'); };
    beforeAll(async () => { await mongoose.connect(uri!, { dbName }); const session = await mongoose.startSession(); try { await session.withTransaction(async () => undefined); } finally { await session.endSession(); } await Promise.all([User.syncIndexes(), Patient.syncIndexes(), Pharmacy.syncIndexes(), PharmacyRequest.syncIndexes(), PharmacyHistory.syncIndexes(), Notification.syncIndexes(), NotificationRecipient.syncIndexes(), NotificationDelivery.syncIndexes()]); });
    afterAll(async () => { if (mongoose.connection.db) await mongoose.connection.db.dropDatabase(); await mongoose.disconnect(); }); afterEach(() => mock.restore());
    beforeEach(async () => { await Promise.all([User.deleteMany({}), Patient.deleteMany({}), Pharmacy.deleteMany({}), PharmacyRequest.deleteMany({}), PharmacyHistory.deleteMany({}), PharmacyCounter.deleteMany({}), Notification.deleteMany({}), NotificationRecipient.deleteMany({}), NotificationDelivery.deleteMany({})]); const users = await User.create(['Patient A', 'Patient B', 'Admin', 'Pharmacy A', 'Pharmacy B'].map((full_name, i) => ({ full_name, phone: `078${Date.now()}${i}`, password_hash: 'hash', role: i < 2 ? 'patient' : i === 2 ? 'admin' : 'pharmacy', status: 'active', is_phone_verified: true }))); patient = await Patient.create({ user_id: users[0]._id, full_name: 'Patient A', phone: users[0].phone, status: 'active' }); patientB = await Patient.create({ user_id: users[1]._id, full_name: 'Patient B', phone: users[1].phone, status: 'active' }); admin = users[2]; pharmacyA = await Pharmacy.create({ user_id: users[3]._id, name: 'Pharmacy A', phone: users[3].phone, address: { address_text: 'Baghdad pharmacy A' }, status: 'active', accepts_prescription_requests: true }); pharmacyB = await Pharmacy.create({ user_id: users[4]._id, name: 'Pharmacy B', phone: users[4].phone, address: { address_text: 'Baghdad pharmacy B' }, status: 'active', accepts_prescription_requests: true }); });
    async function request(status: string = PharmacyStatus.OPEN, pharmacy: any = null, workflowVersion = 0, quoteVersion = 0) { sequence += 1; const quotation = quoteVersion ? { version: quoteVersion, pharmacy_id: pharmacy._id, items: [{ name: 'private medicine', quantity: 1, unit_price: 1000, line_total: 1000 }], unavailable_items: [], medicines_subtotal: 1000, delivery_fee: 0, discount: 0, total_price: 1000, pharmacy_note: 'private pharmacy note', quoted_at: new Date(), accepted_at: null } : null; return PharmacyRequest.create({ request_number: `RX-8C-${sequence}`, patient_id: patient._id, prescription_images: ['private-prescription.png'], treatment_details: 'private treatment details', delivery_address: { address_text: 'Baghdad address', lat: 33.3, lng: 44.3 }, delivery_phone: '0780000000', preferred_payment_method: 'cash_on_delivery', status, workflowVersion, dispatch: { status: pharmacy ? 'CLAIMED' : 'OPEN', mode: 'OPEN_POOL', pharmacy_id: pharmacy?._id ?? null, assigned_at: pharmacy ? new Date() : null, assigned_by_user_id: null, version: workflowVersion }, quotation, accepted_quotation: null, excluded_pharmacy_ids: [] }); }
    const notifications = (item: any, type: string) => Notification.find({ 'source.id': item._id, type }).lean();
    const recipientIds = async (items: any[]) => (await NotificationRecipient.find({ notification_id: { $in: items.map(x => x._id) } }).lean()).map(x => String(x.user_id)).sort();
    async function assertTargeted(items: any[], users: any[]) { expect(await recipientIds(items)).toEqual(users.map(x => String(x)).sort()); expect(await NotificationDelivery.countDocuments({ notification_id: { $in: items.map(x => x._id) }, user_id: { $in: users } })).toBe(users.length); }

    test('claim, direct assignment, reassignment and unassignment use canonical users without a pool broadcast', async () => { const claimed = await request(); await service.claim(String(pharmacyA.user_id), String(claimed._id), actor(pharmacyA.user_id, 'PHARMACY')); const claim = await notifications(claimed, Type.PHARMACY_UNDER_REVIEW); await assertTargeted(claim, [patient.user_id]); expect(String((await NotificationRecipient.findOne({ notification_id: claim[0]._id }))?.user_id)).not.toBe(String(patient._id)); expect(claim[0]).toMatchObject({ category: 'medications', privacy: 'sensitive', source: { domain: 'pharmacy_treatment_request' }, target: { type: 'pharmacy_treatment_request' } }); expect(JSON.stringify(claim[0])).not.toMatch(/private medicine|private treatment|prescription|icon_url|background_color|badge_color/); const assigned = await request(); await service.adminAssign(String(assigned._id), String(pharmacyA._id), undefined, actor(admin, 'ADMIN')); await assertTargeted(await notifications(assigned, Type.PHARMACY_UNDER_REVIEW), [patient.user_id, pharmacyA.user_id]); await service.adminReset('reassign', String(assigned._id), String(pharmacyB._id), 'reason', actor(admin, 'ADMIN')); const reassignOnly = (await notifications(assigned, Type.PHARMACY_UNDER_REVIEW)).filter(x => x.dedupe_key?.includes(':reassigned:')); await assertTargeted(reassignOnly, [patient.user_id, pharmacyB.user_id]); await service.adminReset('unassign', String(assigned._id), undefined, 'reason', actor(admin, 'ADMIN')); const final = await PharmacyRequest.findById(assigned._id).lean(); expect(final).toMatchObject({ status: PharmacyStatus.OPEN, dispatch: { status: 'OPEN', pharmacy_id: null } }); expect(await NotificationRecipient.countDocuments({ user_id: { $in: [pharmacyA.user_id, pharmacyB.user_id] }, notification_id: { $in: (await notifications(assigned, Type.PHARMACY_UNDER_REVIEW)).map(x => x._id) } })).toBe(2); });
    test('quotation revision, acceptance and fulfillment create exactly the expected durable Patient events', async () => { const item = await request(); await service.claim(String(pharmacyA.user_id), String(item._id), actor(pharmacyA.user_id, 'PHARMACY')); await service.quote(String(pharmacyA.user_id), String(item._id), quote(), actor(pharmacyA.user_id, 'PHARMACY')); const first = await notifications(item, Type.PHARMACY_QUOTATION_READY); await assertTargeted(first, [patient.user_id]); await service.quote(String(pharmacyA.user_id), String(item._id), quote(2000), actor(pharmacyA.user_id, 'PHARMACY')); const revised = await notifications(item, Type.PHARMACY_QUOTATION_READY); expect(revised).toHaveLength(2); expect(new Set(revised.map(x => x.dedupe_key)).size).toBe(2); const current = await PharmacyRequest.findById(item._id).lean(); await service.decide(patient._id, String(item._id), current!.quotation!.version, true, undefined, actor(patient.user_id, 'PATIENT')); await assertTargeted(await notifications(item, Type.PHARMACY_CONFIRMED), [patient.user_id, pharmacyA.user_id]); for (const [from, to, type] of [[PharmacyStatus.CONFIRMED, PharmacyStatus.PREPARING, Type.PHARMACY_PREPARING], [PharmacyStatus.PREPARING, PharmacyStatus.READY_FOR_DELIVERY, Type.PHARMACY_READY_FOR_DELIVERY], [PharmacyStatus.READY_FOR_DELIVERY, PharmacyStatus.OUT_FOR_DELIVERY, Type.PHARMACY_OUT_FOR_DELIVERY], [PharmacyStatus.OUT_FOR_DELIVERY, PharmacyStatus.DELIVERED, Type.PHARMACY_DELIVERED]] as const) { await service.transition(String(pharmacyA.user_id), String(item._id), from, to, actor(pharmacyA.user_id, 'PHARMACY')); await assertTargeted(await notifications(item, type), [patient.user_id]); } });
    test('patient rejection, cancellation matrices, and reopen preserve actor-aware recipients', async () => { const rejectedItem = await request(); await service.claim(String(pharmacyA.user_id), String(rejectedItem._id), actor(pharmacyA.user_id, 'PHARMACY')); await service.quote(String(pharmacyA.user_id), String(rejectedItem._id), quote(), actor(pharmacyA.user_id, 'PHARMACY')); await service.decide(patient._id, String(rejectedItem._id), 1, false, 'reason', actor(patient.user_id, 'PATIENT')); await assertTargeted(await notifications(rejectedItem, Type.PHARMACY_QUOTATION_DECLINED), [pharmacyA.user_id]); const patientCancel = await request(PharmacyStatus.UNDER_REVIEW, pharmacyA); await service.cancelPatient(patient._id, String(patientCancel._id), 'reason', actor(patient.user_id, 'PATIENT')); await assertTargeted(await notifications(patientCancel, Type.PHARMACY_CANCELLED), [pharmacyA.user_id]); const noPharmacy = await request(); await service.cancelPatient(patient._id, String(noPharmacy._id), 'reason', actor(patient.user_id, 'PATIENT')); expect(await notifications(noPharmacy, Type.PHARMACY_CANCELLED)).toHaveLength(0); const adminCancel = await request(PharmacyStatus.UNDER_REVIEW, pharmacyA); await service.adminCancel(String(adminCancel._id), 'reason', actor(admin, 'ADMIN')); await assertTargeted(await notifications(adminCancel, Type.PHARMACY_CANCELLED), [patient.user_id, pharmacyA.user_id]); await service.reopen(String(adminCancel._id), 'reason', actor(admin, 'ADMIN')); await assertTargeted(await notifications(adminCancel, Type.PHARMACY_REOPENED), [patient.user_id]); });
    test('dedupe and post-notification failure preserve one durable Pharmacy bundle', async () => { const item = await request(); await service.claim(String(pharmacyA.user_id), String(item._id), actor(pharmacyA.user_id, 'PHARMACY')); const counts = () => Promise.all([Notification.countDocuments(), NotificationRecipient.countDocuments(), NotificationDelivery.countDocuments()]); const before = await counts(); const committed = await PharmacyRequest.findById(item._id); const session = await mongoose.startSession(); try { await domainNotificationService.pharmacy(committed, 'under_review', [], session, 'patient'); } finally { await session.endSession(); } expect(await counts()).toEqual(before); const original = domainNotificationService.pharmacy; spyOn(domainNotificationService, 'pharmacy').mockImplementation(async (...args: any[]) => { await (original as any).apply(domainNotificationService, args); throw new Error('FORCED_AFTER_NOTIFICATION_APPEND'); }); const rollback = await request(); await rejected(service.claim(String(pharmacyA.user_id), String(rollback._id), actor(pharmacyA.user_id, 'PHARMACY'))); expect((await PharmacyRequest.findById(rollback._id).lean())?.status).toBe(PharmacyStatus.OPEN); expect(await Notification.countDocuments({ 'source.id': rollback._id })).toBe(0); });
    test('claim concurrency and stale ownership leave no orphan targeted records', async () => { const counts = () => Promise.all([Notification.countDocuments(), NotificationRecipient.countDocuments(), NotificationDelivery.countDocuments()]); const race = await request(); const outcomes = await Promise.allSettled([service.claim(String(pharmacyA.user_id), String(race._id), actor(pharmacyA.user_id, 'PHARMACY')), service.claim(String(pharmacyB.user_id), String(race._id), actor(pharmacyB.user_id, 'PHARMACY'))]); expect(outcomes.filter(x => x.status === 'fulfilled')).toHaveLength(1); await assertTargeted(await notifications(race, Type.PHARMACY_UNDER_REVIEW), [patient.user_id]); const staleBefore = await counts(); await rejected(service.transition(String(pharmacyA.user_id), String(race._id), PharmacyStatus.CONFIRMED, PharmacyStatus.PREPARING, actor(pharmacyA.user_id, 'PHARMACY'))); expect(await counts()).toEqual(staleBefore); });
    test('missing canonical Pharmacy and Patient mappings roll back workflow mutations', async () => { const missingPharmacy = await request(); await Pharmacy.collection.updateOne({ _id: pharmacyA._id }, { $unset: { user_id: '' } }); await rejected(service.adminAssign(String(missingPharmacy._id), String(pharmacyA._id), undefined, actor(admin, 'ADMIN'))); expect((await PharmacyRequest.findById(missingPharmacy._id).lean())?.status).toBe(PharmacyStatus.OPEN); const missingPatient = await request(); await Patient.collection.updateOne({ _id: patient._id }, { $unset: { user_id: '' } }); await rejected(service.claim(String(pharmacyB.user_id), String(missingPatient._id), actor(pharmacyB.user_id, 'PHARMACY'))); expect((await PharmacyRequest.findById(missingPatient._id).lean())?.status).toBe(PharmacyStatus.OPEN); expect(await Notification.countDocuments({ 'source.id': { $in: [missingPharmacy._id, missingPatient._id] } })).toBe(0); });
});
