import {afterAll,beforeAll,beforeEach,describe,expect,test} from 'bun:test';
import mongoose from 'mongoose';
import notificationService from '../src/services/notification.service';
import Notification from '../src/models/notifications.model';
import NotificationRecipient from '../src/models/notification-recipient.model';
import NotificationDelivery from '../src/models/notification-delivery.model';

const uri=process.env.MONGODB_TEST_URI,run=uri?describe:describe.skip;
run('New-core createAndDispatch durable migration',()=>{beforeAll(async()=>{await mongoose.connect(uri!);await Promise.all([Notification.syncIndexes(),NotificationRecipient.syncIndexes(),NotificationDelivery.syncIndexes()])});beforeEach(async()=>{await mongoose.connection.dropDatabase();await Promise.all([Notification.syncIndexes(),NotificationRecipient.syncIndexes(),NotificationDelivery.syncIndexes()])});afterAll(async()=>{await mongoose.connection.dropDatabase();await mongoose.disconnect()});const payload=(ids:any[])=>({recipient_ids:ids,recipient_model:'User' as const,type:'general' as const,title:'title',body:'body',category:'system' as const});test('persists targeted notification, recipients, and durable rows without provider delivery',async()=>{const users=[new mongoose.Types.ObjectId(),new mongoose.Types.ObjectId()],n=await notificationService.createAndDispatch(payload(users));expect(n).toBeTruthy();expect(await NotificationRecipient.countDocuments({notification_id:n!._id})).toBe(2);expect(await NotificationDelivery.countDocuments({notification_id:n!._id,status:'pending'})).toBe(2)});test('createAndDispatchOnce is idempotent durable work',async()=>{const users=[new mongoose.Types.ObjectId(),new mongoose.Types.ObjectId()],key='phase8b-once';const [a,b]=await Promise.all([notificationService.createAndDispatchOnce(payload(users),key),notificationService.createAndDispatchOnce(payload(users),key)]);expect(String(a?._id)).toBe(String(b?._id));expect(await Notification.countDocuments({dedupe_key:key})).toBe(1);expect(await NotificationRecipient.countDocuments({notification_id:a!._id})).toBe(2);expect(await NotificationDelivery.countDocuments({notification_id:a!._id})).toBe(2)});test('scheduled public create enqueues and cancellation stops pending delivery',async()=>{const scheduled=new Date(Date.now()+3600000),n=await notificationService.createAndDispatch({recipient_ids:[],recipient_model:'all',type:'general',title:'title',body:'body',category:'system',scheduled_at:scheduled});let d=await NotificationDelivery.findOne({notification_id:n!._id}).lean();expect(d).toMatchObject({status:'pending'});expect(d?.next_attempt_at.getTime()).toBe(scheduled.getTime());await notificationService.cancel(String(n!._id));d=await NotificationDelivery.findById(d!._id).lean();expect(d).toMatchObject({status:'cancelled',next_attempt_at:null})})});
