import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'bun:test';
import mongoose from 'mongoose';
import User from '../src/models/users.model';
import Pharmacy from '../src/models/pharmacy.model';
import TreatmentRequest from '../src/models/pharmacy-treatment-request.model';
import History from '../src/models/pharmacy-treatment-request-history.model';
import ActivityLog from '../src/models/activity-log.model';
import Counter from '../src/models/pharmacy-treatment-request-counter.model';
import { PharmacyTreatmentRequestService } from '../src/services/pharmacy-treatment-request.service';
import { assertPharmacyTransactionSupport, MongoosePharmacyTransactionRunner } from '../src/services/pharmacy-transaction.service';
import { PharmacyRequestStatusEnum as S } from '../src/interfaces/pharmacy-treatment-request.interface';

const mongoUri=process.env.MONGODB_TEST_URI,describeWithMongo=mongoUri?describe:describe.skip;
describeWithMongo('Pharmacy workflow transactions against MongoDB replica set',()=>{
    const databaseName=`cannula_pharmacy_workflow_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    const service=new PharmacyTreatmentRequestService();
    const patientId=new mongoose.Types.ObjectId(),patientUserId=new mongoose.Types.ObjectId(),adminId=new mongoose.Types.ObjectId();
    let pharmacies:{profile:any;user:any}[]=[];
    const actor=(user:string,type:'PATIENT'|'PHARMACY'|'ADMIN')=>({user_id:user,type,endpoint:'/integration-test'} as const);

    beforeAll(async()=>{await mongoose.connect(mongoUri!,{dbName:databaseName});await assertPharmacyTransactionSupport();await Promise.all([User.syncIndexes(),Pharmacy.syncIndexes(),TreatmentRequest.syncIndexes(),History.syncIndexes()]);});
    afterAll(async()=>{if(mongoose.connection.db)await mongoose.connection.db.dropDatabase();await mongoose.disconnect();});
    beforeEach(async()=>{await Promise.all([User.deleteMany({}),Pharmacy.deleteMany({}),TreatmentRequest.deleteMany({}),History.deleteMany({}),ActivityLog.deleteMany({}),Counter.deleteMany({})]);pharmacies=[];for(let index=0;index<20;index++){const user=await User.create({full_name:`صيدلية ${index}`,phone:`0770000${String(index).padStart(4,'0')}`,password_hash:'test-hash',password_show:'[redacted]',role:'pharmacy',status:'active',is_phone_verified:true,is_email_verified:false});const profile=await Pharmacy.create({user_id:user._id,name:`صيدلية ${index}`,phone:user.phone,address:{address_text:'بغداد'},status:'active',accepts_prescription_requests:true});pharmacies.push({profile,user});}});
    async function request(status:string=S.OPEN,owner:any=null,quoteVersion=0){return TreatmentRequest.create({request_number:`RX-2099-${new mongoose.Types.ObjectId().toString().slice(-6)}`,patient_id:patientId,prescription_images:[],treatment_details:'دواء',delivery_address:{address_text:'بغداد - المنصور',lat:33.3,lng:44.3},delivery_phone:'07700000000',preferred_payment_method:'cash_on_delivery',status,workflowVersion:0,dispatch:{status:owner?'CLAIMED':'OPEN',mode:'OPEN_POOL',pharmacy_id:owner?._id??null,assigned_at:owner?new Date():null,version:owner?1:0},quotation:quoteVersion?{version:quoteVersion,pharmacy_id:owner._id,items:[{name:'دواء',quantity:1,unit_price:1000,line_total:1000}],unavailable_items:[],medicines_subtotal:1000,delivery_fee:0,discount:0,total_price:1000,quoted_at:new Date()}:null,excluded_pharmacy_ids:[]});}

    test('20 concurrent Pharmacy claims yield one owner and one claim history event',async()=>{const item=await request();const results=await Promise.allSettled(pharmacies.map(({user})=>service.claim(String(user._id),String(item._id),actor(String(user._id),'PHARMACY'))));expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(19);const final=await TreatmentRequest.findById(item._id);expect(final?.status).toBe(S.UNDER_REVIEW);expect(final?.workflowVersion).toBe(1);expect(await History.countDocuments({request_id:item._id,event_type:'CLAIMED_BY_PHARMACY'})).toBe(1);});
    test('Pharmacy claim and Admin assignment have exactly one winner',async()=>{const item=await request(),a=pharmacies[0],b=pharmacies[1];const results=await Promise.allSettled([service.claim(String(a.user._id),String(item._id),actor(String(a.user._id),'PHARMACY')),service.adminAssign(String(item._id),String(b.profile._id),undefined,actor(String(adminId),'ADMIN'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);expect([String(a.profile._id),String(b.profile._id)]).toContain(String(final?.dispatch.pharmacy_id));expect(final?.workflowVersion).toBe(1);});
    test('accept vN racing revision vN+1 cannot accept a stale quotation',async()=>{const a=pharmacies[0],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);const results=await Promise.allSettled([service.decide(patientId,String(item._id),1,true,undefined,actor(String(patientUserId),'PATIENT')),service.quote(String(a.user._id),String(item._id),{items:[{name:'دواء',quantity:1,unit_price:2000}],delivery_fee:0,discount:0},actor(String(a.user._id),'PHARMACY'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);if(final?.status===S.CONFIRMED){expect(final.accepted_quotation?.version).toBe(1);expect(final.accepted_quotation?.total_price).toBe(1000);}else{expect(final?.quotation?.version).toBe(2);expect(final?.accepted_quotation).toBeNull();}});
    test('rejection racing revision leaves either a revised owned quote or a clean excluded OPEN request',async()=>{const a=pharmacies[0],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);const results=await Promise.allSettled([service.decide(patientId,String(item._id),1,false,'مرتفع',actor(String(patientUserId),'PATIENT')),service.quote(String(a.user._id),String(item._id),{items:[{name:'دواء',quantity:1,unit_price:2000}],delivery_fee:0,discount:0},actor(String(a.user._id),'PHARMACY'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);if(final?.status===S.OPEN){expect(final.quotation).toBeNull();expect(final.dispatch.pharmacy_id).toBeNull();expect(final.excluded_pharmacy_ids.map(String)).toContain(String(a.profile._id));}else{expect(final?.status).toBe(S.WAITING_CUSTOMER_APPROVAL);expect(final?.quotation?.version).toBe(2);}});
    test('Admin cancellation racing Patient acceptance has one transition and no hybrid',async()=>{const a=pharmacies[0],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);const results=await Promise.allSettled([service.decide(patientId,String(item._id),1,true,undefined,actor(String(patientUserId),'PATIENT')),service.adminCancel(String(item._id),'إلغاء إداري',actor(String(adminId),'ADMIN'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);expect(Boolean(final&&[S.CONFIRMED,S.CANCELLED].includes(final.status as any))).toBe(true);expect(final?.status===S.CONFIRMED?final.accepted_quotation!==null:final?.cancellation_actor_type==='ADMIN').toBe(true);});
    test('Admin reassignment racing old Pharmacy quote never leaves old ownership with a transferred quote',async()=>{const a=pharmacies[0],b=pharmacies[1],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);await Promise.allSettled([service.quote(String(a.user._id),String(item._id),{items:[{name:'دواء',quantity:1,unit_price:2000}],delivery_fee:0,discount:0},actor(String(a.user._id),'PHARMACY')),service.adminReset('reassign',String(item._id),String(b.profile._id),'تغيير تشغيلي',actor(String(adminId),'ADMIN'))]);const final=await TreatmentRequest.findById(item._id);if(String(final?.dispatch.pharmacy_id)===String(b.profile._id)){expect(final?.quotation).toBeNull();expect(final?.status).toBe(S.UNDER_REVIEW);}else{expect(String(final?.dispatch.pharmacy_id)).toBe(String(a.profile._id));expect(final?.quotation?.pharmacy_id.toString()).toBe(String(a.profile._id));}});
    test('two Admin reopen attempts create one transition and one event',async()=>{const item=await request(S.CANCELLED);item.dispatch.status='CLOSED';item.cancelled_at=new Date();item.cancelled_by_user_id=adminId;item.cancellation_actor_type='ADMIN';await item.save();const results=await Promise.allSettled([service.reopen(String(item._id),'إعادة فتح',actor(String(adminId),'ADMIN')),service.reopen(String(item._id),'إعادة فتح',actor(String(new mongoose.Types.ObjectId()),'ADMIN'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((await TreatmentRequest.findById(item._id))?.workflowVersion).toBe(1);expect(await History.countDocuments({request_id:item._id,event_type:'REQUEST_REOPENED'})).toBe(1);});
    test('history insertion failure rolls back the request mutation',async()=>{const item=await request(),a=pharmacies[0];const failingHistory={create:async()=>{throw new Error('injected history failure')}};const rollbackService=new PharmacyTreatmentRequestService(new MongoosePharmacyTransactionRunner(),failingHistory);await expect(rollbackService.claim(String(a.user._id),String(item._id),actor(String(a.user._id),'PHARMACY'))).rejects.toThrow('injected history failure');const final=await TreatmentRequest.findById(item._id);expect(final?.status).toBe(S.OPEN);expect(final?.workflowVersion).toBe(0);expect(final?.dispatch.pharmacy_id).toBeNull();expect(await History.countDocuments({request_id:item._id})).toBe(0);});
});
