import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'bun:test';
import mongoose from 'mongoose';
import User from '../src/models/users.model';
import Pharmacy from '../src/models/pharmacy.model';
import TreatmentRequest from '../src/models/pharmacy-treatment-request.model';
import History from '../src/models/pharmacy-treatment-request-history.model';
import ActivityLog from '../src/models/activity-log.model';
import Counter from '../src/models/pharmacy-treatment-request-counter.model';
import { PharmacyTreatmentRequestService } from '../src/services/pharmacy-treatment-request.service';
import { assertPharmacyTransactionSupport, MongoosePharmacyTransactionRunner } from '../src/services/pharmacy-transaction.service';
import { PharmacyRequestStatusEnum as S } from '../src/interfaces/pharmacy-treatment-request.interface';
import { backfillPharmacyWorkflow } from '../src/migrations/backfill-pharmacy-workflow.migration';

const mongoUri=process.env.MONGODB_TEST_URI,describeWithMongo=mongoUri?describe:describe.skip;
describeWithMongo('Pharmacy workflow transactions against MongoDB replica set',()=>{
    const databaseName=`cannula_pharmacy_workflow_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    const noNotifications={pharmacy:async()=>null};
    const service=new PharmacyTreatmentRequestService(undefined,undefined,noNotifications);
    const patientId=new mongoose.Types.ObjectId(),patientUserId=new mongoose.Types.ObjectId(),adminId=new mongoose.Types.ObjectId();
    let pharmacies:{profile:any;user:any}[]=[];
    const actor=(user:string,type:'PATIENT'|'PHARMACY'|'ADMIN')=>({user_id:user,type,endpoint:'/integration-test'} as const);

    beforeAll(async()=>{await mongoose.connect(mongoUri!,{dbName:databaseName});await assertPharmacyTransactionSupport();await Promise.all([User.syncIndexes(),Pharmacy.syncIndexes(),TreatmentRequest.syncIndexes(),History.syncIndexes()]);});
    afterAll(async()=>{if(mongoose.connection.db)await mongoose.connection.db.dropDatabase();await mongoose.disconnect();});
    beforeEach(async()=>{await Promise.all([User.deleteMany({}),Pharmacy.deleteMany({}),TreatmentRequest.deleteMany({}),History.deleteMany({}),ActivityLog.deleteMany({}),Counter.deleteMany({})]);pharmacies=[];for(let index=0;index<20;index++){const user=await User.create({full_name:`صيدلية ${index}`,phone:`0770000${String(index).padStart(4,'0')}`,password_hash:'test-hash',role:'pharmacy',status:'active',is_phone_verified:true,is_email_verified:false});const profile=await Pharmacy.create({user_id:user._id,name:`صيدلية ${index}`,phone:user.phone,address:{address_text:'بغداد'},status:'active',accepts_prescription_requests:true});pharmacies.push({profile,user});}});
    async function request(status:string=S.OPEN,owner:any=null,quoteVersion=0){return TreatmentRequest.create({request_number:`RX-2099-${new mongoose.Types.ObjectId().toString().slice(-6)}`,patient_id:patientId,prescription_images:[],treatment_details:'دواء',delivery_address:{address_text:'بغداد - المنصور',lat:33.3,lng:44.3},delivery_phone:'07700000000',preferred_payment_method:'cash_on_delivery',status,workflowVersion:0,dispatch:{status:owner?'CLAIMED':'OPEN',mode:'OPEN_POOL',pharmacy_id:owner?._id??null,assigned_at:owner?new Date():null,version:owner?1:0},quotation:quoteVersion?{version:quoteVersion,pharmacy_id:owner._id,items:[{name:'دواء',quantity:1,unit_price:1000,line_total:1000}],unavailable_items:[],medicines_subtotal:1000,delivery_fee:0,discount:0,total_price:1000,quoted_at:new Date()}:null,excluded_pharmacy_ids:[]});}
    async function rejected(operation:Promise<unknown>){try{await operation;}catch(error){return error as any;}throw new Error('Expected operation to reject');}

    test('20 concurrent Pharmacy claims yield one owner and one claim history event',async()=>{const item=await request();const results=await Promise.allSettled(pharmacies.map(({user})=>service.claim(String(user._id),String(item._id),actor(String(user._id),'PHARMACY'))));expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(19);const final=await TreatmentRequest.findById(item._id);expect(final?.status).toBe(S.UNDER_REVIEW);expect(final?.workflowVersion).toBe(1);expect(final?.dispatch.version).toBe(1);expect(final?.dispatch.pharmacy_id).toBeTruthy();const events=await History.find({request_id:item._id,event_type:'CLAIMED_BY_PHARMACY'});expect(events).toHaveLength(1);expect(String(events[0].to_pharmacy_id)).toBe(String(final?.dispatch.pharmacy_id));expect(String(events[0].actor.pharmacy_id)).toBe(String(final?.dispatch.pharmacy_id));});
    test('Pharmacy claim and Admin assignment have exactly one winner',async()=>{const item=await request(),a=pharmacies[0],b=pharmacies[1];const results=await Promise.allSettled([service.claim(String(a.user._id),String(item._id),actor(String(a.user._id),'PHARMACY')),service.adminAssign(String(item._id),String(b.profile._id),undefined,actor(String(adminId),'ADMIN'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);expect([String(a.profile._id),String(b.profile._id)]).toContain(String(final?.dispatch.pharmacy_id));expect(final?.status).toBe(S.UNDER_REVIEW);expect(final?.workflowVersion).toBe(1);expect(final?.dispatch.version).toBe(1);const events=await History.find({request_id:item._id});expect(events).toHaveLength(1);expect(['CLAIMED_BY_PHARMACY','ASSIGNED_BY_ADMIN']).toContain(events[0].event_type);expect(String(events[0].to_pharmacy_id)).toBe(String(final?.dispatch.pharmacy_id));});
    test('accept vN racing revision vN+1 cannot accept a stale quotation',async()=>{const a=pharmacies[0],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);const results=await Promise.allSettled([service.decide(patientId,String(item._id),1,true,undefined,actor(String(patientUserId),'PATIENT')),service.quote(String(a.user._id),String(item._id),{items:[{name:'دواء',quantity:1,unit_price:2000}],delivery_fee:0,discount:0},actor(String(a.user._id),'PHARMACY'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);expect(final?.workflowVersion).toBe(1);expect(final?.dispatch.version).toBe(2);if(final?.status===S.CONFIRMED){expect(final.accepted_quotation?.version).toBe(1);expect(final.accepted_quotation?.total_price).toBe(1000);expect(await History.countDocuments({request_id:item._id,event_type:'QUOTE_ACCEPTED_BY_CUSTOMER'})).toBe(1);}else{expect(final?.quotation?.version).toBe(2);expect(final?.accepted_quotation).toBeNull();expect(await History.countDocuments({request_id:item._id,event_type:'QUOTE_REVISED'})).toBe(1);}});
    test('rejection racing revision leaves either a revised owned quote or a clean excluded OPEN request',async()=>{const a=pharmacies[0],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);const results=await Promise.allSettled([service.decide(patientId,String(item._id),1,false,'مرتفع',actor(String(patientUserId),'PATIENT')),service.quote(String(a.user._id),String(item._id),{items:[{name:'دواء',quantity:1,unit_price:2000}],delivery_fee:0,discount:0},actor(String(a.user._id),'PHARMACY'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);expect(final?.workflowVersion).toBe(1);expect(final?.dispatch.version).toBe(2);if(final?.status===S.OPEN){expect(final.quotation).toBeNull();expect(final.accepted_quotation).toBeNull();expect(final.dispatch.pharmacy_id).toBeNull();expect(final.excluded_pharmacy_ids.map(String)).toContain(String(a.profile._id));const event=await History.findOne({request_id:item._id,event_type:'QUOTE_REJECTED_BY_CUSTOMER'});expect(event?.metadata?.quotation.version).toBe(1);expect(String(event?.from_pharmacy_id)).toBe(String(a.profile._id));}else{expect(final?.status).toBe(S.WAITING_CUSTOMER_APPROVAL);expect(final?.quotation?.version).toBe(2);expect(await History.countDocuments({request_id:item._id,event_type:'QUOTE_REVISED'})).toBe(1);}});
    test('Admin cancellation racing Patient acceptance has one transition and no hybrid',async()=>{const a=pharmacies[0],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);const results=await Promise.allSettled([service.decide(patientId,String(item._id),1,true,undefined,actor(String(patientUserId),'PATIENT')),service.adminCancel(String(item._id),'إلغاء إداري',actor(String(adminId),'ADMIN'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);expect(Boolean(final&&[S.CONFIRMED,S.CANCELLED].includes(final.status as any))).toBe(true);expect(final?.workflowVersion).toBe(1);expect(final?.dispatch.version).toBe(2);expect(final?.status===S.CONFIRMED?final.accepted_quotation!==null:final?.cancellation_actor_type==='ADMIN').toBe(true);expect(await History.countDocuments({request_id:item._id,event_type:final?.status===S.CONFIRMED?'QUOTE_ACCEPTED_BY_CUSTOMER':'REQUEST_CANCELLED'})).toBe(1);});
    test('Admin reassignment racing old Pharmacy quote never leaves old ownership with a transferred quote',async()=>{const a=pharmacies[0],b=pharmacies[1],item=await request(S.WAITING_CUSTOMER_APPROVAL,a.profile,1);const results=await Promise.allSettled([service.quote(String(a.user._id),String(item._id),{items:[{name:'دواء',quantity:1,unit_price:2000}],delivery_fee:0,discount:0},actor(String(a.user._id),'PHARMACY')),service.adminReset('reassign',String(item._id),String(b.profile._id),'تغيير تشغيلي',actor(String(adminId),'ADMIN'))]);expect(results.filter(x=>x.status==='fulfilled').length).toBeGreaterThanOrEqual(1);const final=await TreatmentRequest.findById(item._id),events=await History.find({request_id:item._id}).sort({createdAt:1,_id:1}),last=events[events.length-1];if(String(final?.dispatch.pharmacy_id)===String(b.profile._id)){expect(final?.quotation).toBeNull();expect(final?.status).toBe(S.UNDER_REVIEW);expect(final?.workflowVersion).toBe(events.length);expect(final?.dispatch.version).toBe(1+events.length);expect(last?.event_type).toBe('REASSIGNED_BY_ADMIN');expect(String(last?.to_pharmacy_id)).toBe(String(b.profile._id));}else{expect(events).toHaveLength(1);expect(final?.workflowVersion).toBe(1);expect(final?.dispatch.version).toBe(2);expect(String(final?.dispatch.pharmacy_id)).toBe(String(a.profile._id));expect(final?.quotation?.version).toBe(2);expect(final?.quotation?.pharmacy_id.toString()).toBe(String(a.profile._id));expect(events[0].event_type).toBe('QUOTE_REVISED');}});
    test('two Admin reopen attempts create one transition and one event',async()=>{const item=await request(S.CANCELLED);const exclusion=pharmacies[0].profile._id;item.dispatch.status='CLOSED';item.excluded_pharmacy_ids=[exclusion];item.cancelled_at=new Date();item.cancelled_by_user_id=adminId;item.cancellation_actor_type='ADMIN';await item.save();const results=await Promise.allSettled([service.reopen(String(item._id),'إعادة فتح',actor(String(adminId),'ADMIN')),service.reopen(String(item._id),'إعادة فتح',actor(String(new mongoose.Types.ObjectId()),'ADMIN'))]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);const final=await TreatmentRequest.findById(item._id);expect(final?.status).toBe(S.OPEN);expect(final?.workflowVersion).toBe(1);expect(final?.dispatch.version).toBe(1);expect(final?.dispatch.pharmacy_id).toBeNull();expect(final?.quotation).toBeNull();expect(final?.excluded_pharmacy_ids.map(String)).toEqual([String(exclusion)]);expect(await History.countDocuments({request_id:item._id,event_type:'REQUEST_REOPENED'})).toBe(1);});
    test('post-confirmation fulfillment preserves accepted terms and rejects other actors and Pharmacies',async()=>{
        const a=pharmacies[0],b=pharmacies[1],item=await request(S.CONFIRMED,a.profile,1),acceptedAt=new Date();
        item.quotation!.accepted_at=acceptedAt;item.accepted_quotation={...(item.quotation as any).toObject(),accepted_at:acceptedAt} as any;await item.save();
        const acceptedSnapshot=JSON.parse(JSON.stringify(item.accepted_quotation));
        expect(await rejected(service.transition(String(b.user._id),String(item._id),S.CONFIRMED,S.PREPARING,actor(String(b.user._id),'PHARMACY')))).toMatchObject({status:404});
        expect(await rejected(service.cancelPatient(patientId,String(item._id),'late',actor(String(patientUserId),'PATIENT')))).toMatchObject({status:409,code:'INVALID_STATE_TRANSITION'});
        expect(await rejected(service.adminCancel(String(item._id),'late',actor(String(adminId),'ADMIN')))).toMatchObject({status:409,code:'INVALID_STATE_TRANSITION'});
        expect(await rejected(service.adminReset('reassign',String(item._id),String(b.profile._id),'late',actor(String(adminId),'ADMIN')))).toMatchObject({status:409,code:'INVALID_STATE_TRANSITION'});
        expect(await History.countDocuments({request_id:item._id})).toBe(0);
        const steps=[[S.CONFIRMED,S.PREPARING],[S.PREPARING,S.READY_FOR_DELIVERY],[S.READY_FOR_DELIVERY,S.OUT_FOR_DELIVERY],[S.OUT_FOR_DELIVERY,S.DELIVERED]] as const;
        for(let index=0;index<steps.length;index++){const[from,to]=steps[index];await service.transition(String(a.user._id),String(item._id),from,to,actor(String(a.user._id),'PHARMACY'));const current=await TreatmentRequest.findById(item._id);expect(current?.status).toBe(to);expect(current?.workflowVersion).toBe(index+1);expect(current?.dispatch.version).toBe(index+2);expect(JSON.parse(JSON.stringify(current?.accepted_quotation))).toEqual(acceptedSnapshot);}
        expect(await rejected(service.transition(String(a.user._id),String(item._id),S.OUT_FOR_DELIVERY,S.DELIVERED,actor(String(a.user._id),'PHARMACY')))).toMatchObject({status:409,code:'INVALID_STATE_TRANSITION'});
        const final=await TreatmentRequest.findById(item._id),events=await History.find({request_id:item._id}).sort({createdAt:1,_id:1});expect(final?.dispatch.status).toBe('CLOSED');expect(events).toHaveLength(4);expect(events.map(event=>[event.from_status,event.to_status])).toEqual(steps.map(step=>[...step]));for(const event of events){expect(event.actor.type).toBe('PHARMACY');expect(String(event.actor.user_id)).toBe(String(a.user._id));expect(String(event.actor.pharmacy_id)).toBe(String(a.profile._id));expect(String(event.to_pharmacy_id)).toBe(String(a.profile._id));expect(event.quotation_version).toBe(1);expect(event.total_price).toBe(1000);expect(event.createdAt).toBeInstanceOf(Date);}
    });
    test('workflow migration preserves representative legacy, malformed, and mixed-version data idempotently',async()=>{
        const pharmacyId=pharmacies[0].profile._id,childId=new mongoose.Types.ObjectId(),createdAt=new Date('2025-01-01T00:00:00.000Z'),updatedAt=new Date('2025-01-02T00:00:00.000Z');
        const quote={version:3,pharmacy_id:pharmacyId,items:[{name:'دواء',quantity:1,unit_price:1000,line_total:1000,note:'legacy line'}],unavailable_items:[],medicines_subtotal:1000,delivery_fee:250,discount:50,total_price:1200,pharmacy_note:'legacy quote',quoted_at:new Date('2025-01-01T12:00:00.000Z'),accepted_at:null};
        const accepted={...quote,accepted_at:updatedAt};
        const base=(request_number:string,status:string)=>({_id:new mongoose.Types.ObjectId(),request_number,patient_id:patientId,child_id:childId,prescription_images:['prescriptions/private-legacy-key.jpg'],treatment_details:'legacy treatment',delivery_address:{address_text:'بغداد - legacy',lat:33.3,lng:44.3},delivery_phone:'07700000000',notes:'legacy note',preferred_payment_method:'cash_on_delivery',status,dispatch:{status:'OPEN',mode:'OPEN_POOL',pharmacy_id:null,assigned_at:null,assigned_by_user_id:null,version:0},quotation:null,accepted_quotation:null,excluded_pharmacy_ids:[],cancelled_at:null,cancelled_by_user_id:null,cancellation_actor_type:null,cancellation_reason:null,createdAt,updatedAt});
        const open=base('RX-MIG-OPEN',S.OPEN);
        const openExcluded={...base('RX-MIG-OPEN-EXCLUDED',S.OPEN),excluded_pharmacy_ids:[pharmacyId]};
        const claimed={...base('RX-MIG-CLAIMED',S.UNDER_REVIEW),dispatch:{status:'CLAIMED',mode:'OPEN_POOL',pharmacy_id:pharmacyId,assigned_at:createdAt,assigned_by_user_id:null,version:4}};
        const quoted={...base('RX-MIG-QUOTED',S.WAITING_CUSTOMER_APPROVAL),dispatch:{status:'CLAIMED',mode:'OPEN_POOL',pharmacy_id:pharmacyId,assigned_at:createdAt,assigned_by_user_id:null,version:5},quotation:quote};
        const cancelled={...base('RX-MIG-CANCELLED',S.CANCELLED),excluded_pharmacy_ids:[pharmacyId],cancelled_at:updatedAt,cancelled_by_user_id:adminId,cancellation_actor_type:'ADMIN',cancellation_reason:'legacy cancellation'};
        const reopened={...base('RX-MIG-REOPENED',S.OPEN),excluded_pharmacy_ids:[pharmacyId]};
        const confirmed={...base('RX-MIG-CONFIRMED',S.CONFIRMED),dispatch:{status:'CLAIMED',mode:'ADMIN_DIRECT',pharmacy_id:pharmacyId,assigned_at:createdAt,assigned_by_user_id:adminId,version:6},quotation:quote};
        const preparing={...base('RX-MIG-PREPARING',S.PREPARING),dispatch:{status:'CLAIMED',mode:'OPEN_POOL',pharmacy_id:pharmacyId,assigned_at:createdAt,assigned_by_user_id:null,version:8},quotation:quote,accepted_quotation:accepted};
        const malformed={...base('RX-MIG-MALFORMED',S.OPEN),dispatch:{status:'CLAIMED',mode:'OPEN_POOL',pharmacy_id:pharmacyId,assigned_at:createdAt,assigned_by_user_id:null,version:2},quotation:quote};
        const existingSeven={...base('RX-MIG-VERSION-7',S.CONFIRMED),workflowVersion:7,dispatch:{status:'CLAIMED',mode:'OPEN_POOL',pharmacy_id:pharmacyId,assigned_at:createdAt,assigned_by_user_id:null,version:7},quotation:{...quote,version:4},accepted_quotation:{...accepted,version:4}};
        const existingZero={...base('RX-MIG-VERSION-0',S.OPEN),workflowVersion:0};
        const fixtures=[open,openExcluded,claimed,quoted,cancelled,reopened,confirmed,preparing,malformed,existingSeven,existingZero];
        await TreatmentRequest.collection.insertMany(fixtures as any[]);
        await History.collection.insertMany([{request_id:claimed._id,request_number:claimed.request_number,event_type:'CLAIMED_BY_PHARMACY',actor:{type:'PHARMACY',user_id:pharmacies[0].user._id,pharmacy_id:pharmacyId},from_status:S.OPEN,to_status:S.UNDER_REVIEW,from_pharmacy_id:null,to_pharmacy_id:pharmacyId,createdAt},{request_id:reopened._id,request_number:reopened.request_number,event_type:'REQUEST_REOPENED',actor:{type:'ADMIN',user_id:adminId,pharmacy_id:null},from_status:S.CANCELLED,to_status:S.OPEN,from_pharmacy_id:pharmacyId,to_pharmacy_id:null,reason:'legacy reopen',createdAt:updatedAt}]);
        const ids=fixtures.map(item=>item._id),historyIds=[claimed._id,reopened._id],snapshot=(value:unknown)=>JSON.parse(JSON.stringify(value)),before=await TreatmentRequest.collection.find({_id:{$in:ids}}).sort({request_number:1}).toArray(),historyBefore=await History.collection.find({request_id:{$in:historyIds}}).sort({createdAt:1,_id:1}).toArray();
        expect(await backfillPharmacyWorkflow()).toEqual({versions:9,acceptedSnapshots:1});
        const after=await TreatmentRequest.collection.find({_id:{$in:ids}}).sort({request_number:1}).toArray(),byNumber=new Map(after.map(doc=>[doc.request_number,doc]));
        for(const original of before){const migrated=byNumber.get(original.request_number)!;const hadVersion=Object.prototype.hasOwnProperty.call(original,'workflowVersion');expect(migrated.workflowVersion).toBe(hadVersion?original.workflowVersion:0);const originalStable=snapshot(original),migratedStable=snapshot(migrated);delete originalStable.workflowVersion;delete migratedStable.workflowVersion;if(original.request_number==='RX-MIG-CONFIRMED'){delete originalStable.accepted_quotation;delete migratedStable.accepted_quotation;}expect(migratedStable).toEqual(originalStable);}
        expect(snapshot(byNumber.get('RX-MIG-CONFIRMED')!.accepted_quotation)).toEqual(snapshot({...quote,accepted_at:updatedAt}));expect(byNumber.get('RX-MIG-VERSION-7')!.workflowVersion).toBe(7);expect(byNumber.get('RX-MIG-VERSION-0')!.workflowVersion).toBe(0);
        expect(snapshot(await History.collection.find({request_id:{$in:historyIds}}).sort({createdAt:1,_id:1}).toArray())).toEqual(snapshot(historyBefore));
        expect(await backfillPharmacyWorkflow()).toEqual({versions:0,acceptedSnapshots:0});
        expect(snapshot(await TreatmentRequest.collection.find({_id:{$in:ids}}).sort({request_number:1}).toArray())).toEqual(snapshot(after));
    });
    test('history insertion failure rolls back the request mutation',async()=>{const item=await request(),a=pharmacies[0];const failingHistory={create:async()=>{throw new Error('injected history failure')}};const rollbackService=new PharmacyTreatmentRequestService(new MongoosePharmacyTransactionRunner(),failingHistory,noNotifications);let failure:unknown;try{await rollbackService.claim(String(a.user._id),String(item._id),actor(String(a.user._id),'PHARMACY'));}catch(error){failure=error;}expect(failure).toBeInstanceOf(Error);expect((failure as Error).message).toContain('injected history failure');const final=await TreatmentRequest.findById(item._id);expect(final?.status).toBe(S.OPEN);expect(final?.workflowVersion).toBe(0);expect(final?.dispatch.version).toBe(0);expect(final?.dispatch.pharmacy_id).toBeNull();expect(final?.accepted_quotation).toBeNull();expect(await History.countDocuments({request_id:item._id})).toBe(0);});
});
