import {afterEach,beforeEach,describe,expect,mock,spyOn,test} from 'bun:test';
import mongoose from 'mongoose';
import {UPLOAD_POLICIES,UploadPurposeEnum} from '../src/constants/upload-policy';
import {R2ConfigurationError,loadR2ConfigFromEnv,resetR2ConfigCacheForTests} from '../src/constants/r2.config';
import {inspectImage} from '../src/services/storage.service';
import uploadPolicyService from '../src/services/upload-policy.service'; import storageService from '../src/services/storage.service';
import MediaAsset from '../src/models/media-asset.model'; import Patient from '../src/models/patients.model'; import Doctor from '../src/models/doctors.model'; import Admin from '../src/models/admins.model'; import ActivityLogService from '../src/services/activity-log.service';
import {IUserRoleEnum} from '../src/interfaces/user.interface'; import {TokenAudienceEnum} from '../src/constants/jwt'; import {MediaAssetStatusEnum} from '../src/interfaces/media-asset.interface'; import {IAdminPermissionEnum} from '../src/interfaces/admin.interface';
import {sanitizeCredentialData} from '../src/services/credential-sanitizer';
import {createUploadController} from '../src/controller/shared/upload.controller'; import sessionService from '../src/services/session.service'; import {signAccessToken,signRefreshToken} from '../src/constants/jwt';
const uid='507f191e810c19729de86401',patientId='507f191e810c19729de86402',otherId='507f191e810c19729de86403';
const chain=<T>(value:T)=>({select(){return this},lean(){return this},exec:async()=>value});
const patientActor={userId:uid,role:IUserRoleEnum.PATIENT,audience:TokenAudienceEnum.MOBILE};
const png=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,6,0,0,0]);
function env(extra:Record<string,string>={}):NodeJS.ProcessEnv{return{NODE_ENV:'test',R2_ACCESS_KEY_ID:'test-access',R2_SECRET_ACCESS_KEY:'secret-never-returned',R2_BUCKET_NAME:'public-bucket',R2_PRIVATE_BUCKET_NAME:'private-bucket',R2_ENDPOINT:'http://127.0.0.1:19000',R2_PUBLIC_URL:'https://cdn.example.test',...extra}}
function asset(overrides:Record<string,unknown>={}){return{_id:new mongoose.Types.ObjectId(),upload_id:'11111111-1111-4111-8111-111111111111',purpose:UploadPurposeEnum.PATIENT_PROFILE_PHOTO,owner_user_id:new mongoose.Types.ObjectId(uid),owner_role:IUserRoleEnum.PATIENT,target_type:'PATIENT',target_id:new mongoose.Types.ObjectId(patientId),pending_key:'pending/id.png',object_key:'public/patients/profile/random.png',expected_content_type:'image/png',max_bytes:5*1024*1024,visibility:'PUBLIC',status:MediaAssetStatusEnum.PENDING,pending_expires_at:new Date(Date.now()+60_000),actual_bytes:null,public_url:null,...overrides}}
beforeEach(()=>{Object.assign(process.env,env(),{ACCESS_TOKEN_SECRET:'phase4-access-secret-long-enough',REFRESH_TOKEN_SECRET:'phase4-refresh-secret-long-enough'});resetR2ConfigCacheForTests();spyOn(ActivityLogService,'logActivity').mockResolvedValue({} as never)});
afterEach(()=>{mock.restore();for(const key of ['R2_ACCESS_KEY_ID','R2_SECRET_ACCESS_KEY','R2_BUCKET_NAME','R2_PRIVATE_BUCKET_NAME','R2_ENDPOINT','R2_PUBLIC_URL','R2_PRESIGN_EXPIRES_IN','R2_MAX_UPLOAD_BYTES'])delete process.env[key];resetR2ConfigCacheForTests()});

describe('central upload policies and configuration',()=>{
 test('only real Cannula media purposes exist and GIF/SVG/HTML are absent',()=>{expect(Object.keys(UPLOAD_POLICIES)).toHaveLength(13);for(const policy of Object.values(UPLOAD_POLICIES))expect(policy.contentTypes).toEqual(['image/jpeg','image/png','image/webp']);expect(UPLOAD_POLICIES.PRESCRIPTION_IMAGE.visibility).toBe('PRIVATE');expect(UPLOAD_POLICIES.AD_IMAGE.roles).toEqual([IUserRoleEnum.ADMIN]);expect(UPLOAD_POLICIES.DOCTOR_PROFILE_PHOTO.roles).not.toContain(IUserRoleEnum.PATIENT)});
 test('config uses secure bounded defaults without exposing values in errors',()=>{const config=loadR2ConfigFromEnv(env());expect(config?.presignExpiresIn).toBe(600);expect(config?.maxUploadBytes).toBe(8*1024*1024);expect(()=>loadR2ConfigFromEnv(env({R2_PRESIGN_EXPIRES_IN:'8640000'}))).toThrow(R2ConfigurationError);expect(()=>loadR2ConfigFromEnv(env({NODE_ENV:'production',R2_ENDPOINT:'https://account.r2.cloudflarestorage.com',R2_PUBLIC_URL:'http://cdn.example.test'}))).toThrow('R2_CONFIG_INVALID:R2_PUBLIC_URL');expect(()=>loadR2ConfigFromEnv({R2_ACCESS_KEY_ID:'secret-id'})).toThrow('R2_CONFIG_INCOMPLETE');try{loadR2ConfigFromEnv(env({R2_MAX_UPLOAD_BYTES:'999999999'}))}catch(error){expect(String(error)).not.toContain('999999999')}});
 test('credential sanitizer redacts signed URLs and signature material',()=>{expect(sanitizeCredentialData({uploadUrl:'signed',presignedUrl:'signed',signature:'sig','X-Amz-Credential':'credential','X-Amz-Security-Token':'token'})).toEqual({uploadUrl:'[REDACTED]',presignedUrl:'[REDACTED]',signature:'[REDACTED]','X-Amz-Credential':'[REDACTED]','X-Amz-Security-Token':'[REDACTED]'})});
});

describe('image signature and decompression bounds',()=>{
 test('accepts bounded PNG, JPEG, and WebP signatures',()=>{expect(inspectImage(png,'image/png')).toEqual({width:1,height:1});expect(inspectImage(new Uint8Array([255,216,255,192,0,17,8,0,1,0,1]),'image/jpeg')).toEqual({width:1,height:1});const webp=new Uint8Array(30);webp.set([82,73,70,70],0);webp.set([87,69,66,80],8);webp.set([86,80,56,88],12);expect(inspectImage(webp,'image/webp')).toEqual({width:1,height:1})});
 test('rejects HTML spoofing, wrong signatures, and excessive pixels',()=>{expect(inspectImage(new TextEncoder().encode('<html><script>'),'image/jpeg')).toBeNull();const huge=png.slice();huge.set([0,1,0,0],16);huge.set([0,1,0,0],20);expect(inspectImage(huge,'image/png')).toBeNull();expect(inspectImage(png,'image/jpeg')).toBeNull()});
});

describe('purpose ownership and opaque intent keys',()=>{
 beforeEach(()=>{spyOn(Patient,'findById').mockImplementation((()=>chain({_id:patientId,user_id:uid})) as never);spyOn(Patient,'findOne').mockImplementation((()=>chain({_id:patientId})) as never);spyOn(MediaAsset,'countDocuments').mockResolvedValue(0);spyOn(storageService,'createPresignedPut').mockResolvedValue({uploadUrl:'https://signed.invalid/?X-Amz-Signature=redacted',expiresIn:600})});
 test('Patient can create only an own profile intent; client folder, key, filename and PII cannot affect the key',async()=>{let stored:any;spyOn(MediaAsset,'create').mockImplementation(async(value:any)=>{stored={_id:new mongoose.Types.ObjectId(),...value};return stored});const first=await uploadPolicyService.initiate({purpose:UploadPurposeEnum.PATIENT_PROFILE_PHOTO,targetId:patientId,contentType:'image/jpeg',folder:'ads',fileName:'../07700000000-evil.html',key:'chosen'} as any,patientActor);expect(first).not.toHaveProperty('publicUrl');expect(stored.pending_key).toMatch(/^pending\/[0-9a-f-]+\.jpg$/);expect(stored.object_key).toMatch(/^public\/patients\/profile\/[0-9a-f-]+\.jpg$/);expect(stored.object_key).not.toContain('07700000000');expect(stored.object_key).not.toContain('html')});
 test('Patient is denied Admin purposes and another Patient target',async()=>{await expect(uploadPolicyService.initiate({purpose:UploadPurposeEnum.AD_IMAGE,contentType:'image/png'},patientActor)).rejects.toMatchObject({code:'UPLOAD_PURPOSE_FORBIDDEN'});spyOn(Patient,'findById').mockImplementation((()=>chain({_id:otherId,user_id:otherId})) as never);await expect(uploadPolicyService.initiate({purpose:UploadPurposeEnum.PATIENT_PROFILE_PHOTO,targetId:otherId,contentType:'image/png'},patientActor)).rejects.toMatchObject({code:'UPLOAD_TARGET_NOT_OWNED'})});
 test('Doctor cannot target another Doctor and Nurse has no self-upload purpose',async()=>{spyOn(Doctor,'findById').mockImplementation((()=>chain({_id:otherId})) as never);spyOn(Doctor,'findOne').mockImplementation((()=>chain({_id:patientId})) as never);await expect(uploadPolicyService.initiate({purpose:UploadPurposeEnum.DOCTOR_PROFILE_PHOTO,targetId:otherId,contentType:'image/png'},{userId:uid,role:IUserRoleEnum.DOCTOR,audience:TokenAudienceEnum.DASHBOARD})).rejects.toMatchObject({code:'UPLOAD_TARGET_NOT_OWNED'});await expect(uploadPolicyService.initiate({purpose:UploadPurposeEnum.NURSE_PROFILE_PHOTO,targetId:otherId,contentType:'image/png'},{userId:uid,role:IUserRoleEnum.NURSE,audience:TokenAudienceEnum.DASHBOARD})).rejects.toMatchObject({code:'UPLOAD_PURPOSE_FORBIDDEN'})});
 test('Admin permission is required and super-admin bypass remains',async()=>{spyOn(Admin,'findOne').mockImplementation((()=>chain({permissions:[],super_admin:false})) as never);await expect(uploadPolicyService.initiate({purpose:UploadPurposeEnum.AD_IMAGE,contentType:'image/png'},{userId:uid,role:IUserRoleEnum.ADMIN,audience:TokenAudienceEnum.DASHBOARD})).rejects.toMatchObject({status:403});mock.restore();spyOn(ActivityLogService,'logActivity').mockResolvedValue({} as never);spyOn(Admin,'findOne').mockImplementation((()=>chain({permissions:[],super_admin:true})) as never);spyOn(MediaAsset,'countDocuments').mockResolvedValue(0);spyOn(MediaAsset,'create').mockImplementation(async(value:any)=>({_id:new mongoose.Types.ObjectId(),...value}) as never);spyOn(storageService,'createPresignedPut').mockResolvedValue({uploadUrl:'signed',expiresIn:600});await expect(uploadPolicyService.initiate({purpose:UploadPurposeEnum.AD_IMAGE,contentType:'image/png'},{userId:uid,role:IUserRoleEnum.ADMIN,audience:TokenAudienceEnum.DASHBOARD})).resolves.toHaveProperty('uploadId')});
 test('outstanding pending intents enforce a per-identity abuse bound',async()=>{spyOn(MediaAsset,'countDocuments').mockResolvedValueOnce(5).mockResolvedValueOnce(5);await expect(uploadPolicyService.initiate({purpose:UploadPurposeEnum.PATIENT_PROFILE_PHOTO,targetId:patientId,contentType:'image/png'},patientActor)).rejects.toMatchObject({status:429,code:'UPLOAD_RATE_LIMITED'})});
});

describe('upload endpoint audience and session isolation',()=>{
 const controller=createUploadController('Upload',[IUserRoleEnum.PATIENT],TokenAudienceEnum.MOBILE),sid='12345678-1234-4234-8234-123456789012';
 const body={purpose:UploadPurposeEnum.PATIENT_PROFILE_PHOTO,targetId:patientId,contentType:'image/png'};
 const call=(authorization:string)=>controller.handle(new Request('http://localhost/upload/intents',{method:'POST',headers:{authorization,'content-type':'application/json'},body:JSON.stringify(body)}));
 test('Mobile access token reaches the upload service while Dashboard and refresh tokens are rejected',async()=>{spyOn(sessionService,'validateAccess').mockImplementation(async p=>({sid:p.sid,userId:p._id,role:p.role,audience:p.aud,restricted:false,currentRefreshDigest:'x',createdAt:'',lastSeenAt:'',lastRefreshedAt:'',expiresAt:''}));const initiate=spyOn(uploadPolicyService,'initiate').mockResolvedValue({uploadId:'id'} as never);const mobile=signAccessToken({_id:uid,role:IUserRoleEnum.PATIENT,sid,audience:TokenAudienceEnum.MOBILE});expect((await call(`Bearer ${mobile}`)).status).toBe(201);expect(initiate).toHaveBeenCalledTimes(1);const dash=signAccessToken({_id:uid,role:IUserRoleEnum.PATIENT,sid,audience:TokenAudienceEnum.DASHBOARD});expect((await call(`Bearer ${dash}`)).status).toBe(401);const refresh=signRefreshToken({_id:uid,role:IUserRoleEnum.PATIENT,sid,jti:crypto.randomUUID(),audience:TokenAudienceEnum.MOBILE,restricted:false});expect((await call(`Bearer ${refresh}`)).status).toBe(401)});
 test('restricted and revoked sessions cannot initiate upload',async()=>{const access=signAccessToken({_id:uid,role:IUserRoleEnum.PATIENT,sid,audience:TokenAudienceEnum.MOBILE});const initiate=spyOn(uploadPolicyService,'initiate').mockResolvedValue({} as never);spyOn(sessionService,'validateAccess').mockResolvedValueOnce({sid,userId:uid,role:IUserRoleEnum.PATIENT,audience:TokenAudienceEnum.MOBILE,restricted:true,currentRefreshDigest:'x',createdAt:'',lastSeenAt:'',lastRefreshedAt:'',expiresAt:''}).mockResolvedValueOnce(null);expect((await call(`Bearer ${access}`)).status).toBe(403);expect((await call(`Bearer ${access}`)).status).toBe(401);expect(initiate).not.toHaveBeenCalled()});
});

describe('authoritative completion and attachment',()=>{
 test('valid object becomes READY and retry is idempotent',async()=>{const pending=asset(),ready=asset({status:MediaAssetStatusEnum.READY,pending_expires_at:null,actual_bytes:png.length,public_url:'https://cdn.example.test/public/x.png'});const found=[pending,ready];spyOn(MediaAsset,'findOne').mockImplementation((()=>chain(found.shift())) as never);spyOn(MediaAsset,'findOneAndUpdate').mockImplementation((()=>chain(pending)) as never);spyOn(MediaAsset,'findByIdAndUpdate').mockImplementation((()=>chain(ready)) as never);spyOn(Patient,'findById').mockImplementation((()=>chain({_id:patientId})) as never);spyOn(Patient,'findOne').mockImplementation((()=>chain({_id:patientId})) as never);spyOn(storageService,'headObject').mockResolvedValue({contentType:'image/png',contentLength:png.length});spyOn(storageService,'readObjectPrefix').mockResolvedValue(png);const promote=spyOn(storageService,'promoteObject').mockResolvedValue();spyOn(storageService,'buildPublicUrl').mockReturnValue('https://cdn.example.test/public/x.png');expect((await uploadPolicyService.complete(pending.upload_id,patientActor)).reference).toBe('https://cdn.example.test/public/x.png');expect((await uploadPolicyService.complete(pending.upload_id,patientActor)).reference).toBe('https://cdn.example.test/public/x.png');expect(promote).toHaveBeenCalledTimes(1)});
 test('oversize, MIME mismatch, and magic mismatch reject and attempt cleanup',async()=>{for(const scenario of [{head:{contentType:'image/png',contentLength:6*1024*1024},bytes:png,code:'UPLOAD_TOO_LARGE'},{head:{contentType:'image/jpeg',contentLength:10},bytes:png,code:'UPLOAD_CONTENT_MISMATCH'},{head:{contentType:'image/png',contentLength:10},bytes:new TextEncoder().encode('not png'),code:'UPLOAD_CONTENT_MISMATCH'}]){mock.restore();spyOn(ActivityLogService,'logActivity').mockResolvedValue({} as never);const pending=asset();spyOn(MediaAsset,'findOne').mockImplementation((()=>chain(pending)) as never);spyOn(MediaAsset,'findOneAndUpdate').mockImplementation((()=>chain(pending)) as never);spyOn(MediaAsset,'updateOne').mockResolvedValue({} as never);spyOn(Patient,'findById').mockImplementation((()=>chain({_id:patientId})) as never);spyOn(Patient,'findOne').mockImplementation((()=>chain({_id:patientId})) as never);spyOn(storageService,'headObject').mockResolvedValue(scenario.head);spyOn(storageService,'readObjectPrefix').mockResolvedValue(scenario.bytes);const cleanup=spyOn(storageService,'deleteObject').mockResolvedValue();await expect(uploadPolicyService.complete(pending.upload_id,patientActor)).rejects.toMatchObject({code:scenario.code});expect(cleanup).toHaveBeenCalled()}});
 test('external, pending, cross-purpose, and cross-target references are rejected',async()=>{const found=[null,asset(),asset({status:MediaAssetStatusEnum.READY,purpose:UploadPurposeEnum.AD_IMAGE}),asset({status:MediaAssetStatusEnum.READY,target_id:new mongoose.Types.ObjectId(otherId)})];spyOn(MediaAsset,'findOne').mockImplementation((()=>chain(found.shift())) as never);for(const expected of ['UPLOAD_NOT_READY','UPLOAD_NOT_READY','UPLOAD_PURPOSE_MISMATCH','UPLOAD_TARGET_NOT_OWNED'])await expect(uploadPolicyService.requireReadyReference('https://evil.example/x.png',UploadPurposeEnum.PATIENT_PROFILE_PHOTO,'PATIENT',patientId)).rejects.toMatchObject({code:expected})});
 test('missing, expired, rejected, and foreign-owner completion states are deterministic',async()=>{const cases:[[any,any],...[any,any][]]=[[null,{code:'UPLOAD_NOT_FOUND'}],[asset({pending_expires_at:new Date(0)}),{code:'UPLOAD_EXPIRED'}],[asset({status:MediaAssetStatusEnum.REJECTED}),{code:'UPLOAD_ALREADY_REJECTED'}],[asset({owner_user_id:new mongoose.Types.ObjectId(otherId)}),{code:'UPLOAD_TARGET_NOT_OWNED'}]];for(const[current,expected]of cases){mock.restore();spyOn(ActivityLogService,'logActivity').mockResolvedValue({} as never);spyOn(MediaAsset,'findOne').mockImplementation((()=>chain(current)) as never);await expect(uploadPolicyService.complete('11111111-1111-4111-8111-111111111111',patientActor)).rejects.toMatchObject(expected)}});
 test('a missing provider object is rejected and cleanup remains safe',async()=>{const pending=asset();spyOn(MediaAsset,'findOne').mockImplementation((()=>chain(pending)) as never);spyOn(MediaAsset,'findOneAndUpdate').mockImplementation((()=>chain(pending)) as never);spyOn(MediaAsset,'updateOne').mockResolvedValue({} as never);spyOn(Patient,'findById').mockImplementation((()=>chain({_id:patientId})) as never);spyOn(Patient,'findOne').mockImplementation((()=>chain({_id:patientId})) as never);spyOn(storageService,'headObject').mockResolvedValue(null);const cleanup=spyOn(storageService,'deleteObject').mockResolvedValue();await expect(uploadPolicyService.complete(pending.upload_id,patientActor)).rejects.toMatchObject({code:'UPLOAD_OBJECT_MISSING'});expect(cleanup).toHaveBeenCalled()});
});
