export const SWAGGER_TAGS = {
    DASHBOARD: {
        AUTH: 'Dashboard - Auth',
        SHARED: 'Dashboard - Shared',
    },
    ADMIN: {
        CLINICS: 'Admin - Clinics',
        DOCTORS: 'Admin - Doctors',
        PATIENTS: 'Admin - Patients',
        APPOINTMENTS: 'Admin - Appointments',
        HOME_CARE: 'Admin - Home Care',
        NOTIFICATIONS: 'Admin - Notifications',
        ADS: 'Admin - Ads',
        ACTIVITY_LOGS: 'Admin - Activity Logs',
        SPECIALTIES: 'Admin - Specialties',
        CHRONIC_CONDITIONS: 'Admin - Chronic Conditions',
        SUGGESTIONS: 'Admin - Suggestions',
        ABOUT_US: 'Admin - About Us',
    },
    DOCTOR: {
        PROFILE: 'Doctor - Profile',
        APPOINTMENTS: 'Doctor - Appointments',
        SECRETARIES: 'Doctor - Secretaries',
        SUGGESTIONS: 'Doctor - Suggestions',
        ACTIVITY_LOGS: 'Doctor - Activity Logs',
    },
    MOBILE: {
        AUTH: 'Mobile - Auth',
        PROFILE: 'Mobile - Profile',
        HEALTH_PROFILE: 'Mobile - Health Profile',
        CHILDREN: 'Mobile - Children',
        DOCTORS: 'Mobile - Doctors',
        FAVORITES: 'Mobile - Favorites',
        APPOINTMENTS: 'Mobile - Appointments',
        HOME_CARE: 'Mobile - Home Care',
        SPECIALTIES: 'Mobile - Specialties',
        CHRONIC_CONDITIONS: 'Mobile - Chronic Conditions',
        SUGGESTIONS: 'Mobile - Suggestions',
        ADS: 'Mobile - Ads',
        ABOUT_US: 'Mobile - About Us',
    },
} as const;

export const SWAGGER_TAG_DEFINITIONS = [
    { name: SWAGGER_TAGS.DASHBOARD.AUTH, 'x-displayName': 'Auth', description: 'المصادقة وإدارة جلسات لوحة التحكم' },
    { name: SWAGGER_TAGS.DASHBOARD.SHARED, 'x-displayName': 'Shared', description: 'الخدمات المشتركة بين أدوار لوحة التحكم' },
    { name: SWAGGER_TAGS.ADMIN.CLINICS, 'x-displayName': 'Clinics', description: 'إدارة العيادات' },
    { name: SWAGGER_TAGS.ADMIN.DOCTORS, 'x-displayName': 'Doctors', description: 'إدارة الأطباء' },
    { name: SWAGGER_TAGS.ADMIN.PATIENTS, 'x-displayName': 'Patients', description: 'إدارة المرضى' },
    { name: SWAGGER_TAGS.ADMIN.APPOINTMENTS, 'x-displayName': 'Appointments', description: 'إدارة المواعيد' },
    { name: SWAGGER_TAGS.ADMIN.HOME_CARE, 'x-displayName': 'Home Care', description: 'إدارة خدمات وطلبات الرعاية المنزلية' },
    { name: SWAGGER_TAGS.ADMIN.NOTIFICATIONS, 'x-displayName': 'Notifications', description: 'إدارة الإشعارات' },
    { name: SWAGGER_TAGS.ADMIN.ADS, 'x-displayName': 'Ads', description: 'إدارة الإعلانات' },
    { name: SWAGGER_TAGS.ADMIN.ACTIVITY_LOGS, 'x-displayName': 'Activity Logs', description: 'عرض سجلات نشاط الإدارة' },
    { name: SWAGGER_TAGS.ADMIN.SPECIALTIES, 'x-displayName': 'Specialties', description: 'إدارة التخصصات الطبية' },
    { name: SWAGGER_TAGS.ADMIN.CHRONIC_CONDITIONS, 'x-displayName': 'Chronic Conditions', description: 'إدارة الأمراض المزمنة' },
    { name: SWAGGER_TAGS.ADMIN.SUGGESTIONS, 'x-displayName': 'Suggestions', description: 'إدارة الاقتراحات' },
    { name: SWAGGER_TAGS.ADMIN.ABOUT_US, 'x-displayName': 'About Us', description: 'إدارة محتوى من نحن' },
    { name: SWAGGER_TAGS.DOCTOR.PROFILE, 'x-displayName': 'Profile', description: 'إدارة الملف الشخصي للطبيب' },
    { name: SWAGGER_TAGS.DOCTOR.APPOINTMENTS, 'x-displayName': 'Appointments', description: 'إدارة مواعيد الطبيب' },
    { name: SWAGGER_TAGS.DOCTOR.SECRETARIES, 'x-displayName': 'Secretaries', description: 'إدارة سكرتارية الطبيب' },
    { name: SWAGGER_TAGS.DOCTOR.SUGGESTIONS, 'x-displayName': 'Suggestions', description: 'اقتراحات الطبيب' },
    { name: SWAGGER_TAGS.DOCTOR.ACTIVITY_LOGS, 'x-displayName': 'Activity Logs', description: 'عرض سجلات نشاط الطبيب' },
    { name: SWAGGER_TAGS.MOBILE.AUTH, 'x-displayName': 'Auth', description: 'المصادقة والتسجيل في تطبيق المريض' },
    { name: SWAGGER_TAGS.MOBILE.PROFILE, 'x-displayName': 'Profile', description: 'إدارة الملف الشخصي للمريض' },
    { name: SWAGGER_TAGS.MOBILE.HEALTH_PROFILE, 'x-displayName': 'Health Profile', description: 'إدارة الملف الصحي للمريض' },
    { name: SWAGGER_TAGS.MOBILE.CHILDREN, 'x-displayName': 'Children', description: 'إدارة أطفال المريض' },
    { name: SWAGGER_TAGS.MOBILE.DOCTORS, 'x-displayName': 'Doctors', description: 'استعراض الأطباء في تطبيق المريض' },
    { name: SWAGGER_TAGS.MOBILE.FAVORITES, 'x-displayName': 'Favorites', description: 'إدارة الأطباء المفضلين' },
    { name: SWAGGER_TAGS.MOBILE.APPOINTMENTS, 'x-displayName': 'Appointments', description: 'حجز وإدارة مواعيد المريض' },
    { name: SWAGGER_TAGS.MOBILE.HOME_CARE, 'x-displayName': 'Home Care', description: 'خدمات وطلبات الرعاية المنزلية في تطبيق المريض' },
    { name: SWAGGER_TAGS.MOBILE.SPECIALTIES, 'x-displayName': 'Specialties', description: 'استعراض التخصصات الطبية' },
    { name: SWAGGER_TAGS.MOBILE.CHRONIC_CONDITIONS, 'x-displayName': 'Chronic Conditions', description: 'استعراض الأمراض المزمنة' },
    { name: SWAGGER_TAGS.MOBILE.SUGGESTIONS, 'x-displayName': 'Suggestions', description: 'اقتراحات المريض' },
    { name: SWAGGER_TAGS.MOBILE.ADS, 'x-displayName': 'Ads', description: 'عرض الإعلانات في تطبيق المريض' },
    { name: SWAGGER_TAGS.MOBILE.ABOUT_US, 'x-displayName': 'About Us', description: 'عرض محتوى من نحن في تطبيق المريض' },
];

export const SWAGGER_TAG_GROUPS = [
    { name: 'Dashboard', tags: [SWAGGER_TAGS.DASHBOARD.AUTH, SWAGGER_TAGS.DASHBOARD.SHARED] },
    {
        name: 'Admin',
        tags: [
            SWAGGER_TAGS.ADMIN.CLINICS,
            SWAGGER_TAGS.ADMIN.DOCTORS,
            SWAGGER_TAGS.ADMIN.PATIENTS,
            SWAGGER_TAGS.ADMIN.APPOINTMENTS,
            SWAGGER_TAGS.ADMIN.HOME_CARE,
            SWAGGER_TAGS.ADMIN.NOTIFICATIONS,
            SWAGGER_TAGS.ADMIN.ADS,
            SWAGGER_TAGS.ADMIN.ACTIVITY_LOGS,
            SWAGGER_TAGS.ADMIN.SPECIALTIES,
            SWAGGER_TAGS.ADMIN.CHRONIC_CONDITIONS,
            SWAGGER_TAGS.ADMIN.SUGGESTIONS,
            SWAGGER_TAGS.ADMIN.ABOUT_US,
        ],
    },
    {
        name: 'Doctor',
        tags: [
            SWAGGER_TAGS.DOCTOR.PROFILE,
            SWAGGER_TAGS.DOCTOR.APPOINTMENTS,
            SWAGGER_TAGS.DOCTOR.SECRETARIES,
            SWAGGER_TAGS.DOCTOR.SUGGESTIONS,
            SWAGGER_TAGS.DOCTOR.ACTIVITY_LOGS,
        ],
    },
    {
        name: 'Mobile',
        tags: [
            SWAGGER_TAGS.MOBILE.AUTH,
            SWAGGER_TAGS.MOBILE.PROFILE,
            SWAGGER_TAGS.MOBILE.HEALTH_PROFILE,
            SWAGGER_TAGS.MOBILE.CHILDREN,
            SWAGGER_TAGS.MOBILE.DOCTORS,
            SWAGGER_TAGS.MOBILE.FAVORITES,
            SWAGGER_TAGS.MOBILE.APPOINTMENTS,
            SWAGGER_TAGS.MOBILE.HOME_CARE,
            SWAGGER_TAGS.MOBILE.SPECIALTIES,
            SWAGGER_TAGS.MOBILE.CHRONIC_CONDITIONS,
            SWAGGER_TAGS.MOBILE.SUGGESTIONS,
            SWAGGER_TAGS.MOBILE.ADS,
            SWAGGER_TAGS.MOBILE.ABOUT_US,
        ],
    },
];
