import Elysia,{t} from 'elysia'; import {AuthPlugin} from '../../../middleware/auth.middleware'; import {IUserRoleEnum} from '../../../interfaces/user.interface'; import {PharmacyRequestStatusEnum as S} from '../../../interfaces/pharmacy-treatment-request.interface'; import service,{type RxActor} from '../../../services/pharmacy-treatment-request.service'; import {formatPharmacyRequestForAvailable,formatPharmacyRequestForPharmacy} from '../../../services/pharmacy-treatment-request.formatter'; import {DomainError} from '../../../services/domain-error'; import {SWAGGER_TAGS} from '../../../constants/swagger-tags'; import {ConflictResponseSchema,ForbiddenResponseSchema,NotFoundResponseSchema,ProtectedApiErrorResponses,ValidationErrorResponseSchema} from '../../../schemas/api-response.schema'; import {AvailablePharmacyRequestListResponseSchema,PharmacyOwnedRequestListResponseSchema,PharmacyOwnedRequestResponseSchema} from '../../../schemas/pharmacy-response.schema';
const pg=(p:number,l:number,total:number)=>({page:p,limit:l,total,pages:Math.ceil(total/l),hasNext:p<Math.ceil(total/l),hasPrev:p>1}); const role=(r:string)=>{if(r!==IUserRoleEnum.PHARMACY)throw new DomainError('غير مصرح لك بالوصول',403)}; const actor=(id:string,path:string):RxActor=>({user_id:id,type:'PHARMACY',endpoint:path});
const quote=t.Object({items:t.Array(t.Object({name:t.String({minLength:1,maxLength:200}),quantity:t.Integer({minimum:1}),unit_price:t.Integer({minimum:0}),note:t.Optional(t.Nullable(t.String({maxLength:500})))}),{minItems:1,maxItems:100}),unavailable_items:t.Optional(t.Array(t.Object({name:t.String({minLength:1,maxLength:200}),note:t.Optional(t.Nullable(t.String({maxLength:500})))}),{maxItems:100})),delivery_fee:t.Integer({minimum:0}),discount:t.Integer({minimum:0}),pharmacy_note:t.Optional(t.Nullable(t.String({maxLength:2000})))},{additionalProperties:false});
async function owned(uid:string,id:string){const x=await service.getPharmacy(uid,id);if(!x)throw new DomainError('الطلب غير موجود',404);return formatPharmacyRequestForPharmacy(x)}
export const pharmacyTreatmentRequestsController=new Elysia({prefix:'/requests',detail:{tags:[SWAGGER_TAGS.PHARMACY.REQUESTS]}}).use(AuthPlugin()).onError(({error,set})=>{if(error instanceof DomainError){set.status=error.status;return{error:true,message:error.message,code:error.code}}})
.get('/available',async({query,phrase})=>{role(phrase.role);const x=await service.listAvailable(phrase._id,query),p=x.page,l=x.limit;return{error:false,message:'تم جلب طلبات العلاج المتاحة بنجاح',data:x.data.map(formatPharmacyRequestForAvailable),pagination:pg(p,l,x.count)}},{query:t.Object({page:t.Optional(t.String()),limit:t.Optional(t.String())}),response:{200:AvailablePharmacyRequestListResponseSchema,403:ForbiddenResponseSchema,...ProtectedApiErrorResponses}})
.get('/my-requests',async({query,phrase})=>{role(phrase.role);const x=await service.listMine(phrase._id,query);return{error:false,message:'تم جلب طلبات العلاج بنجاح',data:x.data.map(formatPharmacyRequestForPharmacy),pagination:pg(x.page,x.limit,x.count)}},{query:t.Object({page:t.Optional(t.String()),limit:t.Optional(t.String()),status:t.Optional(t.Enum(S)),dateFrom:t.Optional(t.String()),dateTo:t.Optional(t.String())}),response:{200:PharmacyOwnedRequestListResponseSchema,403:ForbiddenResponseSchema,422:ValidationErrorResponseSchema,...ProtectedApiErrorResponses}})
.get('/:id',async({params,phrase})=>{role(phrase.role);return{error:false,message:'تم جلب طلب العلاج بنجاح',data:await owned(phrase._id,params.id)}},{response:{200:PharmacyOwnedRequestResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/claim',async({params,phrase})=>{role(phrase.role);await service.claim(phrase._id,params.id,actor(phrase._id,`/dash/pharmacy/requests/${params.id}/claim`));return{error:false,message:'تم استلام طلب العلاج بنجاح',data:await owned(phrase._id,params.id)}},{response:{200:PharmacyOwnedRequestResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.post('/:id/quotation',async({params,body,phrase})=>{role(phrase.role);await service.quote(phrase._id,params.id,{...body,unavailable_items:body.unavailable_items??[]},actor(phrase._id,`/dash/pharmacy/requests/${params.id}/quotation`));return{error:false,message:'تم إرسال عرض السعر بنجاح',data:await owned(phrase._id,params.id)}},{body:quote,response:{200:PharmacyOwnedRequestResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,409:ConflictResponseSchema,422:ValidationErrorResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/preparing',({params,phrase})=>step(params.id,phrase._id,phrase.role,S.CONFIRMED,S.PREPARING,'تم بدء تجهيز الطلب بنجاح'),{response:{200:PharmacyOwnedRequestResponseSchema,403:ForbiddenResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/ready',({params,phrase})=>step(params.id,phrase._id,phrase.role,S.PREPARING,S.READY_FOR_DELIVERY,'تم تجهيز الطلب للتوصيل بنجاح'),{response:{200:PharmacyOwnedRequestResponseSchema,403:ForbiddenResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/out-for-delivery',({params,phrase})=>step(params.id,phrase._id,phrase.role,S.READY_FOR_DELIVERY,S.OUT_FOR_DELIVERY,'تم إرسال الطلب للتوصيل بنجاح'),{response:{200:PharmacyOwnedRequestResponseSchema,403:ForbiddenResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/delivered',({params,phrase})=>step(params.id,phrase._id,phrase.role,S.OUT_FOR_DELIVERY,S.DELIVERED,'تم تسليم الطلب بنجاح'),{response:{200:PharmacyOwnedRequestResponseSchema,403:ForbiddenResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}});
async function step(id:string,uid:string,r:string,from:any,to:any,message:string){role(r);await service.transition(uid,id,from,to,actor(uid,`/dash/pharmacy/requests/${id}/${to}`));return{error:false,message,data:await owned(uid,id)}}
