import Elysia, { t } from 'elysia';
import mongoose from 'mongoose';
import { safeSearchPattern } from '../../../services/search-safety.service';
import { SWAGGER_TAGS } from '../../../constants/swagger-tags';
import { AuthPlugin } from '../../../middleware/auth.middleware';
import adsService from '../../../services/ads.service';
import { IAdsStatusEnum } from '../../../interfaces/ads.interface';
import { BadRequestResponseSchema, ConflictResponseSchema, GenericDataResponseSchema, GenericPaginatedResponseSchema, NotFoundResponseSchema, ProtectedApiErrorResponses, ValidationErrorResponseSchema } from '../../../schemas/api-response.schema';
import { AdminPermissionGuardPlugin } from '../../../middleware/authorization.middleware';
import { IAdminPermissionEnum } from '../../../interfaces/admin.interface';
import { DomainError } from '../../../services/domain-error';
const ObjectId = mongoose.Types.ObjectId;
const adsBodySchema = t.Object({ title: t.Optional(t.Nullable(t.String({ maxLength: 200 }))), description: t.Optional(t.Nullable(t.String({ maxLength: 2000 }))), image: t.String({ minLength: 1 }), start_date: t.Optional(t.Nullable(t.String({ format: 'date-time' }))), end_date: t.Optional(t.Nullable(t.String({ format: 'date-time' }))), sort_order: t.Optional(t.Integer({ minimum: 0, maximum: 2_147_483_647 })) }, { additionalProperties: false });
const updateSchema = t.Partial(adsBodySchema);
function date(value: string | null | undefined) { if (value === null) return null; if (value === undefined) return undefined; const parsed = new Date(value); if (Number.isNaN(parsed.getTime())) throw new DomainError('تاريخ الإعلان غير صالح', 422, 'INVALID_AD_SCHEDULE'); return parsed; }
function withIsEnded(ad: any) { const obj = ad?.toObject ? ad.toObject() : { ...ad }; return { ...obj, is_ended: obj.end_date != null && new Date(obj.end_date) < new Date() }; }
function meta(phrase: any, endpoint: string) { return { user_id: phrase._id, user_name: phrase.role + '_' + phrase._id, user_type: phrase.role, endpoint, source: 'dashboard' }; }

export const adsController = new Elysia({ prefix: '/ads', detail: { tags: [SWAGGER_TAGS.ADMIN.ADS] } }).use(AuthPlugin()).use(AdminPermissionGuardPlugin(IAdminPermissionEnum.MANAGE_SETTINGS))
    .get('/', async ({ query }) => {
        const page = Math.max(1, Number(query.page) || 1), limit = Math.min(100, Math.max(1, Number(query.limit) || 10)), match: Record<string, unknown> = {}, and: Record<string, unknown>[] = [];
        if (query.status) match.status = query.status;
        const now = new Date(); if (query.is_ended === 'true') and.push({ end_date: { $ne: null, $lt: now } }); else if (query.is_ended === 'false') and.push({ $or: [{ end_date: null }, { end_date: { $gte: now } }] });
        if (query.search) { const search = safeSearchPattern(query.search); and.push({ $or: [{ title: { $regex: search, $options: 'i' } }, { description: { $regex: search, $options: 'i' } }] }); }
        if (and.length) match.$and = and; const { data, count } = await adsService.getPaginated({ main_match: match, page, limit });
        return { error: false, message: 'تم جلب الإعلانات بنجاح', data: data.map(withIsEnded), pagination: { page, limit, total: count, pages: Math.ceil(count / limit), hasNext: page < Math.ceil(count / limit), hasPrev: page > 1 } };
    }, { query: t.Object({ page: t.Optional(t.String()), limit: t.Optional(t.String()), status: t.Optional(t.Enum(IAdsStatusEnum)), is_ended: t.Optional(t.Union([t.Literal('true'), t.Literal('false')])), search: t.Optional(t.String()) }, { additionalProperties: false }), response: { 200: GenericPaginatedResponseSchema, 422: ValidationErrorResponseSchema, ...ProtectedApiErrorResponses } })
    .patch('/order', async ({ body, phrase }) => ({ error: false, message: 'تم تحديث ترتيب الإعلانات بنجاح', data: await adsService.reorder(body.adIds, meta(phrase, '/dash/admin/ads/order')) }), { body: t.Object({ adIds: t.Array(t.String(), { minItems: 1, maxItems: 500 }) }, { additionalProperties: false }), response: { 200: GenericDataResponseSchema, 400: BadRequestResponseSchema, 404: NotFoundResponseSchema, 409: ConflictResponseSchema, 422: ValidationErrorResponseSchema, ...ProtectedApiErrorResponses } })
    .get('/:id', async ({ params, set }) => { if (!ObjectId.isValid(params.id)) { set.status = 400; return { error: true, message: 'معرف الإعلان غير صالح' }; } const ad = await adsService.getById(params.id); if (!ad) { set.status = 404; return { error: true, message: 'الإعلان غير موجود' }; } return { error: false, message: 'تم جلب الإعلان بنجاح', data: withIsEnded(ad) }; }, { params: t.Object({ id: t.String() }), response: { 200: GenericDataResponseSchema, 400: BadRequestResponseSchema, 404: NotFoundResponseSchema, ...ProtectedApiErrorResponses } })
    .post('/', async ({ body, phrase, set }) => { const ad = await adsService.create({ title: body.title, description: body.description, image: body.image, start_date: date(body.start_date), end_date: date(body.end_date), sort_order: body.sort_order }, meta(phrase, '/dash/admin/ads')); set.status = 201; return { error: false, message: 'تم إنشاء الإعلان بنجاح', data: withIsEnded(ad) }; }, { body: adsBodySchema, response: { 201: GenericDataResponseSchema, 400: BadRequestResponseSchema, 422: ValidationErrorResponseSchema, ...ProtectedApiErrorResponses } })
    .put('/:id', async ({ params, body, phrase, set }) => { if (!ObjectId.isValid(params.id)) { set.status = 400; return { error: true, message: 'معرف الإعلان غير صالح' }; } const ad = await adsService.getById(params.id); if (!ad) { set.status = 404; return { error: true, message: 'الإعلان غير موجود' }; } const updated = await adsService.update(params.id, { ...body, start_date: date(body.start_date), end_date: date(body.end_date) }, meta(phrase, '/dash/admin/ads/' + params.id)); return { error: false, message: 'تم تحديث الإعلان بنجاح', data: withIsEnded(updated) }; }, { params: t.Object({ id: t.String() }), body: updateSchema, response: { 200: GenericDataResponseSchema, 400: BadRequestResponseSchema, 404: NotFoundResponseSchema, 422: ValidationErrorResponseSchema, ...ProtectedApiErrorResponses } })
    .patch('/:id/status', async ({ params, body, phrase, set }) => { if (!ObjectId.isValid(params.id)) { set.status = 400; return { error: true, message: 'معرف الإعلان غير صالح' }; } const ad = await adsService.getById(params.id); if (!ad) { set.status = 404; return { error: true, message: 'الإعلان غير موجود' }; } return { error: false, message: 'تم تحديث حالة الإعلان بنجاح', data: withIsEnded(await adsService.updateStatus(params.id, body.status, meta(phrase, '/dash/admin/ads/' + params.id + '/status'))) }; }, { params: t.Object({ id: t.String() }), body: t.Object({ status: t.Enum(IAdsStatusEnum) }, { additionalProperties: false }), response: { 200: GenericDataResponseSchema, 400: BadRequestResponseSchema, 404: NotFoundResponseSchema, 422: ValidationErrorResponseSchema, ...ProtectedApiErrorResponses } });
