import Elysia,{t} from 'elysia'; import {AuthPlugin} from '../../../middleware/auth.middleware'; import {IUserRoleEnum} from '../../../interfaces/user.interface'; import {PharmacyPaymentMethodEnum,PharmacyRequestStatusEnum} from '../../../interfaces/pharmacy-treatment-request.interface'; import service,{type RxActor} from '../../../services/pharmacy-treatment-request.service'; import {formatPharmacyHistory,formatPharmacyRequestForAdmin} from '../../../services/pharmacy-treatment-request.formatter'; import {DomainError} from '../../../services/domain-error'; import {SWAGGER_TAGS} from '../../../constants/swagger-tags'; import {ConflictResponseSchema,ForbiddenResponseSchema,NotFoundResponseSchema,ProtectedApiErrorResponses,ValidationErrorResponseSchema} from '../../../schemas/api-response.schema'; import {AdminPharmacyRequestListResponseSchema,AdminPharmacyRequestResponseSchema,PharmacyHistoryListResponseSchema} from '../../../schemas/pharmacy-response.schema';
import {AdminPermissionGuardPlugin} from '../../../middleware/authorization.middleware'; import {IAdminPermissionEnum} from '../../../interfaces/admin.interface';
const admin=(r:string)=>{if(r!==IUserRoleEnum.ADMIN)throw new DomainError('غير مصرح لك بالوصول',403)};const page=(p:number,l:number,total:number)=>({page:p,limit:l,total,pages:Math.ceil(total/l),hasNext:p<Math.ceil(total/l),hasPrev:p>1});const actor=(id:string,path:string):RxActor=>({user_id:id,type:'ADMIN',endpoint:path});async function detail(id:string){const x=await service.adminGet(id);if(!x)throw new DomainError('الطلب غير موجود',404);return formatPharmacyRequestForAdmin(x)}
export const pharmacyRequestsAdminController=new Elysia({prefix:'/pharmacy-requests',detail:{tags:[SWAGGER_TAGS.ADMIN.PHARMACY_REQUESTS]}}).use(AuthPlugin()).use(AdminPermissionGuardPlugin(IAdminPermissionEnum.MANAGE_PHARMACY_REQUESTS)).onError(({error,set})=>{if(error instanceof DomainError){set.status=error.status;return{error:true,message:error.message,code:error.code}}})
.get('/',async({query,phrase})=>{admin(phrase.role);const x=await service.adminList(query);return{error:false,message:'تم جلب طلبات الصيدليات بنجاح',data:x.data.map(formatPharmacyRequestForAdmin),pagination:page(x.page,x.limit,x.count)}},{query:t.Object({page:t.Optional(t.String()),limit:t.Optional(t.String()),status:t.Optional(t.Enum(PharmacyRequestStatusEnum)),pharmacy_id:t.Optional(t.String()),patient_id:t.Optional(t.String()),dispatch_mode:t.Optional(t.String()),has_quotation:t.Optional(t.String()),request_number:t.Optional(t.String()),dateFrom:t.Optional(t.String()),dateTo:t.Optional(t.String()),payment_method:t.Optional(t.Enum(PharmacyPaymentMethodEnum)),search:t.Optional(t.String())}),response:{200:AdminPharmacyRequestListResponseSchema,403:ForbiddenResponseSchema,422:ValidationErrorResponseSchema,...ProtectedApiErrorResponses}})
.get('/:id',async({params,phrase})=>{admin(phrase.role);return{error:false,message:'تم جلب طلب العلاج بنجاح',data:await detail(params.id)}},{response:{200:AdminPharmacyRequestResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/assign',async({params,body,phrase})=>{admin(phrase.role);await service.adminAssign(params.id,body.pharmacy_id,body.reason??undefined,actor(phrase._id,`/dash/admin/pharmacy-requests/${params.id}/assign`),body.overrideExclusion??false);return{error:false,message:'تم تعيين الصيدلية بنجاح',data:await detail(params.id)}},{body:t.Object({pharmacy_id:t.String(),reason:t.Optional(t.Nullable(t.String({maxLength:1000}))),overrideExclusion:t.Optional(t.Boolean())},{additionalProperties:false}),response:{200:AdminPharmacyRequestResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/reassign',async({params,body,phrase})=>{admin(phrase.role);await service.adminReset('reassign',params.id,body.pharmacy_id,body.reason,actor(phrase._id,`/dash/admin/pharmacy-requests/${params.id}/reassign`));return{error:false,message:'تم إعادة تعيين الصيدلية بنجاح',data:await detail(params.id)}},{body:t.Object({pharmacy_id:t.String(),reason:t.String({minLength:1,maxLength:1000})}),response:{200:AdminPharmacyRequestResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/unassign',async({params,body,phrase})=>{admin(phrase.role);await service.adminReset('unassign',params.id,undefined,body.reason,actor(phrase._id,`/dash/admin/pharmacy-requests/${params.id}/unassign`));return{error:false,message:'تم إلغاء تعيين الصيدلية بنجاح',data:await detail(params.id)}},{body:t.Object({reason:t.String({minLength:1,maxLength:1000})}),response:{200:AdminPharmacyRequestResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/cancel',async({params,body,phrase})=>{admin(phrase.role);await service.adminCancel(params.id,body.reason??'',actor(phrase._id,`/dash/admin/pharmacy-requests/${params.id}/cancel`));return{error:false,message:'تم إلغاء طلب العلاج بنجاح',data:await detail(params.id)}},{body:t.Object({reason:t.Optional(t.String({maxLength:1000}))}),response:{200:AdminPharmacyRequestResponseSchema,403:ForbiddenResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.patch('/:id/reopen',async({params,body,phrase})=>{admin(phrase.role);await service.reopen(params.id,body.reason,actor(phrase._id,`/dash/admin/pharmacy-requests/${params.id}/reopen`));return{error:false,message:'تم إعادة فتح الطلب بنجاح',data:await detail(params.id)}},{body:t.Object({reason:t.String({minLength:1,maxLength:1000})}),response:{200:AdminPharmacyRequestResponseSchema,403:ForbiddenResponseSchema,409:ConflictResponseSchema,...ProtectedApiErrorResponses}})
.get('/:id/history',async({params,query,phrase})=>{admin(phrase.role);if(!await service.adminGet(params.id))throw new DomainError('الطلب غير موجود',404,'PHARMACY_REQUEST_NOT_FOUND');const x=await service.history(params.id,query);return{error:false,message:'تم جلب سجل الطلب بنجاح',data:x.data.map(formatPharmacyHistory),pagination:page(x.page,x.limit,x.count)}},{query:t.Object({page:t.Optional(t.String()),limit:t.Optional(t.String())}),response:{200:PharmacyHistoryListResponseSchema,403:ForbiddenResponseSchema,404:NotFoundResponseSchema,...ProtectedApiErrorResponses}});
